import { Platform, StyleSheet } from 'react-native';
import { BorderRadius, FontSize, Spacing, dropShadow, type ColorScheme } from '../../constants/theme';

/** Styles for the photo and drawing editor, its canvas overlays, controls and sheets. */
export function createPhotoEditorStyles(colors: ColorScheme) {
    return StyleSheet.create({
        container: { flex: 1, backgroundColor: '#111827' },
        // Kept in the stylesheet: react-native-web applies 'box-none' only to compiled styles.
        selectionLayer: { ...StyleSheet.absoluteFill, pointerEvents: 'box-none' },
        header: {
            minHeight: 62,
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: Spacing.md,
            borderBottomWidth: StyleSheet.hairlineWidth,
            borderBottomColor: '#374151',
        },
        headerButton: { minWidth: 64, minHeight: 44, justifyContent: 'center' },
        headerButtonText: { color: '#d1d5db', fontSize: FontSize.md, fontWeight: '600' },
        headerCenter: { flex: 1, alignItems: 'center', paddingHorizontal: Spacing.sm },
        title: { color: '#ffffff', fontSize: FontSize.lg, fontWeight: '800' },
        subtitle: { color: '#9ca3af', fontSize: FontSize.sm, marginTop: 2 },
        saveButton: {
            minWidth: 64,
            minHeight: 44,
            paddingHorizontal: Spacing.md,
            borderRadius: BorderRadius.md,
            backgroundColor: colors.accent,
            alignItems: 'center',
            justifyContent: 'center',
        },
        saveButtonText: { color: '#fff', fontWeight: '800', fontSize: FontSize.md },
        saveButtonDisabled: { opacity: 0.5 },
        stage: { flex: 1, minHeight: 0, overflow: 'hidden', alignItems: 'center', justifyContent: 'center', padding: 8 },
        exportSurface: {
        position: 'absolute',
        // Far enough off screen that it can never be seen, close enough to stay laid out.
        left: -30000,
        top: 0,
        overflow: 'hidden',
    },
    canvas: { backgroundColor: '#000', overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
        controls: {
            backgroundColor: '#1f2937',
            borderTopWidth: StyleSheet.hairlineWidth,
            borderTopColor: '#374151',
            paddingBottom: Platform.OS === 'ios' ? 8 : 12,
        },
        toolList: { paddingHorizontal: Spacing.sm, paddingVertical: 7, gap: 5 },
        toolButton: {
            width: 54,
            minHeight: 52,
            borderRadius: BorderRadius.md,
            alignItems: 'center',
            justifyContent: 'center',
            gap: 2,
        },
        toolButtonActive: { backgroundColor: '#374151' },
        pageSheetOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'flex-end' },
        pageSheet: {
            backgroundColor: '#1f2937',
            borderTopLeftRadius: BorderRadius.lg,
            borderTopRightRadius: BorderRadius.lg,
            paddingHorizontal: Spacing.lg,
            paddingTop: 44,
            paddingBottom: 28,
            gap: Spacing.xs,
        },
        pageSheetTitle: { color: '#ffffff', fontSize: FontSize.lg, fontWeight: '800' },
        sourceRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: Spacing.md,
            paddingVertical: Spacing.md,
            paddingHorizontal: Spacing.sm,
            borderRadius: BorderRadius.md,
            backgroundColor: 'rgba(255, 255, 255, 0.06)',
            marginTop: Spacing.sm,
        },
        sourceRowIcon: { fontSize: FontSize.lg },
        sourceRowText: { color: '#ffffff', fontSize: FontSize.md, fontWeight: '700' },
        sourceCancel: { alignItems: 'center', paddingVertical: Spacing.md, marginTop: Spacing.xs },
        sourceCancelText: { color: '#9ca3af', fontSize: FontSize.md, fontWeight: '700' },
        pageSheetLabel: { color: '#9ca3af', fontSize: FontSize.sm, fontWeight: '600', marginTop: Spacing.sm },
        pageChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
        pageChip: {
            minWidth: 76,
            alignItems: 'center',
            gap: 6,
            paddingVertical: Spacing.sm,
            paddingHorizontal: Spacing.sm,
            borderRadius: BorderRadius.md,
            borderWidth: 2,
            borderColor: '#374151',
            backgroundColor: '#111827',
        },
        pageChipActive: { borderColor: colors.accent, backgroundColor: '#0b1220' },
        pageChipSwatch: { borderRadius: 4, borderWidth: StyleSheet.hairlineWidth, borderColor: '#4b5563' },
        pageChipText: { color: '#9ca3af', fontSize: FontSize.sm, fontWeight: '600' },
        pageChipTextActive: { color: '#ffffff' },
        pageColorDot: {
            width: 44,
            height: 34,
            borderRadius: 4,
            borderWidth: StyleSheet.hairlineWidth,
            borderColor: '#4b5563',
        },
        pageSheetDone: {
            marginTop: Spacing.lg,
            minHeight: 48,
            borderRadius: BorderRadius.md,
            backgroundColor: colors.accent,
            alignItems: 'center',
            justifyContent: 'center',
        },
        pageSheetDoneText: { color: '#ffffff', fontWeight: '800', fontSize: FontSize.md },
        toolIcon: { color: '#f9fafb', fontSize: 20, lineHeight: 23 },
        textToolIcon: { fontWeight: '900' },
        toolLabel: { color: '#9ca3af', fontSize: 10, fontWeight: '600' },
        toolLabelActive: { color: '#ffffff' },
        optionsRow: {
            minHeight: 50,
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: Spacing.sm,
            gap: 4,
        },
        colorList: { alignItems: 'center', gap: 4, paddingRight: 4 },
        colorScroll: { flex: 1 },
        colorButton: {
            width: 36,
            height: 44,
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: BorderRadius.sm,
        },
        colorButtonActive: { backgroundColor: '#4b5563' },
        colorDot: { width: 23, height: 23, borderRadius: 12, borderWidth: 1, borderColor: '#6b7280' },
        sizeGroup: { flexDirection: 'row', alignItems: 'center' },
        sizeButton: { width: 34, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: BorderRadius.sm },
        sizeButtonActive: { backgroundColor: '#4b5563' },
        sizeDot: { borderRadius: 999 },
        historyButton: { width: 42, height: 44, alignItems: 'center', justifyContent: 'center' },
        historyIcon: { color: '#f9fafb', fontSize: 23 },
        disabledText: { color: '#4b5563' },

        // Interactive Text Selection Styles
        textSelectionBox: {
            position: 'absolute',
            borderWidth: 1.5,
            borderColor: colors.accent,
            borderStyle: 'dashed',
            borderRadius: 8,
            overflow: 'visible',
        },
        // The corners are laid out in canvas coordinates rather than inside the frame, so the
        // handle the finger reaches for is drawn at the point the gesture handler tests.
        selectionHandle: {
            position: 'absolute',
            width: 14,
            height: 14,
            borderRadius: 7,
            backgroundColor: '#ffffff',
            borderWidth: 3,
            borderColor: colors.accent,
        },
        selectionHandleActive: {
            backgroundColor: colors.accent,
            borderColor: '#ffffff',
            transform: [{ scale: 1.25 }],
        },
        rotateStem: {
            position: 'absolute',
            left: '50%',
            width: 2,
            marginLeft: -1,
            backgroundColor: colors.accent,
            opacity: 0.9,
        },
        rotateKnob: {
            position: 'absolute',
            width: 30,
            height: 30,
            borderRadius: 15,
            backgroundColor: '#ffffff',
            borderWidth: 2,
            borderColor: colors.accent,
            alignItems: 'center',
            justifyContent: 'center',
        },
        rotateKnobActive: {
            backgroundColor: colors.accent,
            borderColor: '#ffffff',
        },
        rotateKnobIcon: { color: colors.accent, fontSize: FontSize.md, fontWeight: '800' },
        rotateKnobIconActive: { color: '#ffffff' },
        anglePill: {
            position: 'absolute',
            minWidth: 52,
            paddingHorizontal: 8,
            paddingVertical: 4,
            borderRadius: 12,
            backgroundColor: 'rgba(17, 24, 39, 0.94)',
            alignItems: 'center',
        },
        anglePillText: { color: '#ffffff', fontSize: FontSize.sm, fontWeight: '800' },
        // Guides are the one piece of chrome that has to read against ink of any colour, so they
        // take a hue nothing in the palette draws with.
        snapGuide: { position: 'absolute', backgroundColor: '#ff2d95', opacity: 0.9 },
        snapGuideVertical: { top: 0, bottom: 0, width: 2 },
        snapGuideHorizontal: { left: 0, right: 0, height: 2 },
        textFloatingToolbar: {
            position: 'absolute',
            height: 38,
            borderRadius: 19,
            backgroundColor: 'rgba(17, 24, 39, 0.94)',
            borderWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.25)',
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 6,
            gap: 4,
            ...dropShadow({ y: 2, blur: 6, opacity: 0.45 }),
            zIndex: 99,
        },
        textFloatingBtn: {
            width: 34,
            height: 30,
            borderRadius: 15,
            alignItems: 'center',
            justifyContent: 'center',
        },
        textFloatingIcon: {
            color: '#ffffff',
            fontSize: 16,
            fontWeight: '700',
        },
        textFloatingSmallA: {
            color: '#ffffff',
            fontSize: 13,
            fontWeight: '800',
        },
        textFloatingBigA: {
            color: '#ffffff',
            fontSize: 16,
            fontWeight: '900',
        },
        textFloatingDivider: {
            width: 1,
            height: 18,
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
            marginHorizontal: 2,
        },
        textFloatingDeleteBtn: {
            width: 32,
            height: 30,
        },
        textFloatingDeleteIcon: {
            color: '#ef4444',
            fontSize: 16,
        },
        textTrashZone: {
            // Position and size come from `photoTrashPillRect`, the same geometry the drop hit
            // test uses; only the paint lives here.
            position: 'absolute',
            justifyContent: 'center',
            paddingHorizontal: 18,
            borderRadius: 22,
            backgroundColor: 'rgba(31, 41, 55, 0.92)',
            borderWidth: 1.5,
            borderColor: 'rgba(255, 255, 255, 0.3)',
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
            ...dropShadow({ y: 3, blur: 8, opacity: 0.45 }),
            zIndex: 999,
        },
        textTrashZoneHovered: {
            backgroundColor: '#ef4444',
            borderColor: '#fca5a5',
            transform: [{ scale: 1.08 }],
        },
        textTrashIcon: {
            fontSize: 20,
        },
        textTrashIconHovered: {
            transform: [{ scale: 1.15 }],
        },
        textTrashLabel: {
            color: '#ffffff',
            fontSize: FontSize.xs,
            fontWeight: '700',
            // The pill has a fixed width now, so a long translation shortens itself instead of
            // spilling past the edge of the drop target.
            flexShrink: 1,
        },
        textTrashLabelHovered: {
            color: '#ffffff',
            fontWeight: '900',
        },
        textStyleIconBadge: {
            width: 22,
            height: 22,
            borderRadius: 5,
            borderWidth: 1,
            borderColor: '#ffffff',
            alignItems: 'center',
            justifyContent: 'center',
        },
        textStyleBadgeSolid: {
            backgroundColor: '#ffffff',
        },
        textStyleBadgeFrosted: {
            backgroundColor: 'rgba(255, 255, 255, 0.5)',
        },
        textStyleBadgeOutline: {
            backgroundColor: 'transparent',
            borderWidth: 2,
            borderColor: '#38bdf8',
        },
        textStyleIconText: {
            color: '#111827',
            fontSize: 13,
            fontWeight: '900',
        },

        // Crop UI styles
        cropDim: {
            position: 'absolute',
            backgroundColor: 'rgba(0, 0, 0, 0.65)',
        },
        cropBox: {
            position: 'absolute',
            borderWidth: 2,
            borderColor: '#ffffff',
            overflow: 'visible',
        },
        cropGridH: {
            position: 'absolute',
            left: 0,
            right: 0,
            height: StyleSheet.hairlineWidth,
            backgroundColor: 'rgba(255, 255, 255, 0.45)',
        },
        cropGridV: {
            position: 'absolute',
            top: 0,
            bottom: 0,
            width: StyleSheet.hairlineWidth,
            backgroundColor: 'rgba(255, 255, 255, 0.45)',
        },
        cornerHandle: {
            position: 'absolute',
            width: 16,
            height: 16,
            borderColor: '#ffffff',
        },
        cornerTL: { top: -2, left: -2, borderTopWidth: 4, borderLeftWidth: 4 },
        cornerTR: { top: -2, right: -2, borderTopWidth: 4, borderRightWidth: 4 },
        cornerBL: { bottom: -2, left: -2, borderBottomWidth: 4, borderLeftWidth: 4 },
        cornerBR: { bottom: -2, right: -2, borderBottomWidth: 4, borderRightWidth: 4 },
        edgeHandleH: {
            position: 'absolute',
            left: '50%',
            marginLeft: -14,
            width: 28,
            height: 6,
            borderRadius: 3,
            backgroundColor: '#ffffff',
        },
        edgeHandleV: {
            position: 'absolute',
            top: '50%',
            marginTop: -14,
            width: 6,
            height: 28,
            borderRadius: 3,
            backgroundColor: '#ffffff',
        },
        cropControlsContainer: {
            paddingHorizontal: Spacing.sm,
            paddingTop: 4,
            gap: Spacing.xs,
        },
        cropAspectList: {
            alignItems: 'center',
            gap: Spacing.xs,
            paddingVertical: 2,
        },
        cropAspectBtn: {
            paddingHorizontal: 12,
            height: 32,
            borderRadius: BorderRadius.full,
            backgroundColor: '#374151',
            alignItems: 'center',
            justifyContent: 'center',
        },
        cropAspectBtnActive: {
            backgroundColor: colors.accent,
        },
        cropAspectLabel: {
            color: '#9ca3af',
            fontSize: FontSize.xs,
            fontWeight: '600',
        },
        cropAspectLabelActive: {
            color: '#ffffff',
            fontWeight: '700',
        },
        cropActionRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: Spacing.sm,
            paddingVertical: 4,
        },
        cropCancelBtn: {
            flex: 1,
            height: 40,
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: BorderRadius.md,
            backgroundColor: '#374151',
        },
        cropCancelText: {
            color: '#d1d5db',
            fontSize: FontSize.sm,
            fontWeight: '600',
        },
        cropResetBtn: {
            flex: 1,
            height: 40,
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: BorderRadius.md,
            backgroundColor: '#374151',
        },
        cropResetText: {
            color: '#d1d5db',
            fontSize: FontSize.sm,
            fontWeight: '600',
        },
        cropApplyBtn: {
            flex: 1.2,
            height: 40,
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: BorderRadius.md,
            backgroundColor: colors.accent,
        },
        cropApplyText: {
            color: '#ffffff',
            fontSize: FontSize.sm,
            fontWeight: '700',
        },

        eraserIndicator: {
            position: 'absolute',
            borderWidth: 2,
            borderColor: 'rgba(255, 255, 255, 0.95)',
            backgroundColor: 'rgba(239, 68, 68, 0.28)',
            ...dropShadow({ y: 1, blur: 5, opacity: 0.4 }),
            zIndex: 99,
        },
        eraserModeGroup: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            alignSelf: 'center',
            marginHorizontal: Spacing.sm,
            padding: 3,
            borderRadius: BorderRadius.full,
            backgroundColor: '#1f2937',
        },
        eraserModeButton: {
            flex: 1,
            minHeight: 34,
            alignItems: 'center',
            justifyContent: 'center',
            paddingHorizontal: 10,
            borderRadius: BorderRadius.full,
        },
        eraserModeButtonActive: { backgroundColor: '#374151' },
        eraserModeText: {
            color: '#9ca3af',
            fontSize: FontSize.xs,
            fontWeight: '600',
        },
        eraserModeTextActive: { color: '#f9fafb', fontWeight: '800' },

        // Instagram Fullscreen Text Composer Styles
        instagramTextOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.88)',
            justifyContent: 'space-between',
        },
        instagramTextHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: Spacing.md,
            paddingVertical: Spacing.sm,
        },
        instagramHeaderBtn: {
            minWidth: 60,
            height: 44,
            justifyContent: 'center',
        },
        instagramHeaderBtnText: {
            color: '#ffffff',
            fontSize: FontSize.md,
            fontWeight: '600',
        },
        instagramHeaderCenter: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: Spacing.sm,
        },
        instagramToolPill: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: 'rgba(255, 255, 255, 0.16)',
            alignItems: 'center',
            justifyContent: 'center',
        },
        instagramToolPillActive: {
            backgroundColor: 'rgba(255, 255, 255, 0.32)',
        },
        instagramStyleBadge: {
            width: 22,
            height: 22,
            borderRadius: 5,
            borderWidth: 1,
            borderColor: '#ffffff',
            alignItems: 'center',
            justifyContent: 'center',
        },
        instagramStyleBadgeText: {
            color: '#ffffff',
            fontSize: 13,
            fontWeight: '900',
        },
        instagramAlignText: {
            color: '#ffffff',
            fontSize: 20,
            fontWeight: '700',
        },
        instagramDoneBtn: {
            paddingHorizontal: 16,
            height: 38,
            borderRadius: 19,
            backgroundColor: colors.accent,
            alignItems: 'center',
            justifyContent: 'center',
        },
        instagramDoneBtnDisabled: {
            opacity: 0.5,
        },
        instagramDoneBtnText: {
            color: '#ffffff',
            fontSize: FontSize.sm,
            fontWeight: '800',
        },
        instagramCenterWrapper: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: Spacing.md,
        },
        instagramSliderColumn: {
            width: 40,
            alignItems: 'center',
            justifyContent: 'center',
            gap: 6,
        },
        instagramSliderLabel: {
            color: 'rgba(255, 255, 255, 0.85)',
            fontSize: 11,
            fontWeight: '700',
        },
        instagramSliderTrack: {
            width: 6,
            height: 160,
            borderRadius: 3,
            backgroundColor: 'rgba(255, 255, 255, 0.25)',
            alignItems: 'center',
            justifyContent: 'flex-end',
            position: 'relative',
        },
        instagramSliderThumb: {
            position: 'absolute',
            left: -9,
            width: 24,
            height: 24,
            borderRadius: 12,
            backgroundColor: '#ffffff',
            borderWidth: 2,
            borderColor: colors.accent,
            ...dropShadow({ y: 2, blur: 4, opacity: 0.5 }),
        },
        instagramSliderMinLabel: {
            color: 'rgba(255, 255, 255, 0.5)',
            fontSize: 14,
            fontWeight: '800',
        },
        instagramInputContainer: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            paddingHorizontal: Spacing.md,
        },
        instagramTextInput: {
            maxWidth: '100%',
            fontWeight: '800',
            borderRadius: 14,
            paddingHorizontal: 18,
            paddingVertical: 12,
        },
        instagramColorRow: {
            paddingVertical: Spacing.md,
            borderTopWidth: StyleSheet.hairlineWidth,
            borderTopColor: 'rgba(255, 255, 255, 0.12)',
        },
        instagramColorList: {
            paddingHorizontal: Spacing.md,
            gap: Spacing.sm,
            alignItems: 'center',
        },
        instagramColorBtn: {
            width: 40,
            height: 44,
            alignItems: 'center',
            justifyContent: 'center',
        },
        instagramColorBtnActive: {
            transform: [{ scale: 1.18 }],
        },
        instagramColorDot: {
            width: 28,
            height: 28,
            borderRadius: 14,
            borderWidth: 2,
            borderColor: '#ffffff',
        },
    });
}

export type PhotoEditorStyles = ReturnType<typeof createPhotoEditorStyles>;
