import { Platform, StyleSheet } from 'react-native';
import { BorderRadius, FontSize, Shadows, Spacing, type ColorScheme } from '../../constants/theme';

// The overflow menu is drawn over the whole screen, so it has to be told where the header ends:
// the safe-area inset the header sits below, plus the header itself.
export const EDITOR_HEADER_HEIGHT = 56;

/** Styles for the note editor screen and every dialog it opens. */
export function createEditorStyles(colors: ColorScheme) {
    return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.bgCard },
    keyboardArea: { flex: 1 },
    editorHeader: {
        minHeight: EDITOR_HEADER_HEIGHT,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.accent,
        paddingHorizontal: 4,
    },
    headerAction: {
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: BorderRadius.full,
    },
    headerTitle: {
        flexShrink: 1,
        color: colors.white,
        fontSize: FontSize.xl,
        fontWeight: '600',
        marginLeft: 4,
    },
    headerSpacer: { flex: 1 },
    editorScroll: { flex: 1, backgroundColor: colors.bgCard },
    content: {
        width: '100%',
        maxWidth: 720,
        alignSelf: 'center',
        paddingHorizontal: 6,
        paddingTop: 5,
        paddingBottom: Spacing.xxl,
    },
    selectorGroup: {
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: colors.border,
    },
    ankiSelectorRow: {
        minHeight: 50,
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.border,
        paddingHorizontal: Spacing.sm,
    },
    ankiSelectorRowLast: { borderBottomWidth: StyleSheet.hairlineWidth },
    ankiSelectorLabel: { width: 72, fontSize: FontSize.md, fontWeight: '800', color: colors.textPrimary },
    ankiSelectorValue: { flex: 1, fontSize: FontSize.md, color: colors.textPrimary },
    ankiSelectorChevron: { width: 28, height: 40, alignItems: 'center', justifyContent: 'center' },
    formatToolbar: {
        backgroundColor: colors.bgCard,
        borderTopWidth: 1,
        borderTopColor: colors.border,
        minHeight: 44,
    },
    blockStyleButtonText: { fontSize: FontSize.md, fontWeight: '700', color: colors.textPrimary },
    blockStyleButtonTextActive: { color: colors.accent },
    calloutOption: { borderLeftWidth: 4, borderRadius: BorderRadius.sm },
    linkInput: {
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: BorderRadius.sm,
        paddingHorizontal: Spacing.md,
        minHeight: 44,
        fontSize: FontSize.md,
        color: colors.textPrimary,
        marginBottom: Spacing.sm,
        includeFontPadding: false,
        textAlignVertical: 'center',
    },
    toolbarTabsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: Spacing.sm,
        paddingTop: 4,
    },
    toolbarTabs: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: Spacing.xs,
    },
    keyboardDismissButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: BorderRadius.full,
        backgroundColor: colors.accentLight,
    },
    keyboardDismissText: {
        fontSize: FontSize.xs,
        fontWeight: '700',
        color: colors.accent,
    },
    standaloneKeyboardDismissBar: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        paddingHorizontal: Spacing.md,
        paddingVertical: Spacing.xs,
        backgroundColor: colors.bgCard,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: colors.border,
    },
    scrollBottomDismissArea: {
        height: 100,
        width: '100%',
    },
    toolbarTab: {
        paddingHorizontal: Spacing.md,
        minHeight: 32,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: BorderRadius.full,
    },
    toolbarTabActive: { backgroundColor: colors.accentLight },
    toolbarTabText: { fontSize: FontSize.sm, fontWeight: '600', color: colors.textMuted },
    toolbarTabTextActive: { color: colors.accent },
    formatToolbarScroll: { width: '100%' },
    formatToolbarContent: {
        flexGrow: 1,
        minHeight: 44,
        alignItems: 'center',
        paddingHorizontal: 0,
    },
    formatToolbarContentCentered: { justifyContent: 'center' },
    formatToolbarWrapped: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 0,
    },
    formatButton: {
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: BorderRadius.sm,
    },
    formatButtonActive: {
        backgroundColor: colors.accentLight,
    },
    // A tool that cannot apply is greyed rather than silently swallowing the press.
    formatButtonDisabled: { opacity: 0.4 },
    blockStyleButtonTextDisabled: { color: colors.textMuted },
    customFormatButtonText: {
        maxWidth: 38,
        fontSize: 24,
        lineHeight: 28,
        color: colors.textPrimary,
        textAlign: 'center',
    },
    summaryRow: {
        minHeight: 48,
        flexDirection: 'row',
        alignItems: 'center',
        gap: Spacing.sm,
        paddingHorizontal: Spacing.md,
        backgroundColor: colors.bgSecondary,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: BorderRadius.sm,
        marginTop: 5,
    },
    summaryLabel: { fontSize: FontSize.sm, fontWeight: '800', color: colors.textPrimary },
    summaryValue: { flex: 1, fontSize: FontSize.sm, color: colors.textSecondary },
    summaryChevron: { color: colors.textMuted, fontSize: 22, fontWeight: '600' },
    overflowOverlay: {
        ...StyleSheet.absoluteFill,
        alignItems: 'flex-end',
        backgroundColor: 'rgba(0,0,0,0.18)',
        paddingRight: 4,
        zIndex: 100,
        elevation: 100,
    },
    overflowMenu: {
        width: 282,
        paddingVertical: 4,
        backgroundColor: colors.bgCard,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 2,
        overflow: 'hidden',
        ...Shadows.lg,
    },
    overflowItem: {
        minHeight: 50,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        gap: Spacing.sm,
    },
    overflowItemDisabled: { opacity: 0.4 },
    overflowSeparator: {
        height: StyleSheet.hairlineWidth,
        marginVertical: 4,
        backgroundColor: colors.border,
    },
    overflowItemText: { flex: 1, fontSize: FontSize.md, fontWeight: '500', color: colors.textPrimary },
    overflowItemValue: { fontSize: FontSize.sm, color: colors.textSecondary },
    overflowChevron: { fontSize: 23, color: colors.textMuted },
    overflowCheckbox: {
        width: 20,
        height: 20,
        borderRadius: 2,
        borderWidth: 2,
        borderColor: colors.textMuted,
        alignItems: 'center',
        justifyContent: 'center',
    },
    overflowCheckboxChecked: { backgroundColor: colors.accent, borderColor: colors.accent },
    overflowCheckboxMark: { color: colors.white, fontSize: 14, lineHeight: 16, fontWeight: '900' },
    fontSizeOption: {
        minHeight: 48,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: Spacing.md,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.borderLight,
    },
    fontSizeSample: { color: colors.textPrimary },
    dangerText: { color: colors.btnAgain },
    pickerOptionActive: { backgroundColor: colors.accentLight },
    pickerCheck: { fontSize: 20, fontWeight: '800', color: colors.accent },
    formatPickerOption: {
        minHeight: 48,
        justifyContent: 'center',
        paddingHorizontal: Spacing.sm,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.borderLight,
    },
    formatPickerOptionText: { fontSize: FontSize.md, color: colors.textPrimary },
    customToolbarExplanation: {
        marginBottom: Spacing.md,
        fontSize: FontSize.sm,
        lineHeight: 20,
        color: colors.textSecondary,
    },
    customToolbarPresetSection: {
        marginBottom: Spacing.sm,
    },
    customToolbarSectionTitle: {
        fontSize: FontSize.xs,
        fontWeight: '700',
        color: colors.textSecondary,
        marginBottom: Spacing.xs,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    customToolbarPresetScroll: {
        flexDirection: 'row',
        gap: Spacing.xs,
        paddingVertical: 2,
    },
    customToolbarPresetChip: {
        paddingHorizontal: Spacing.sm,
        paddingVertical: 6,
        backgroundColor: colors.bgSecondary,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: BorderRadius.full,
    },
    customToolbarPresetChipText: {
        fontSize: FontSize.xs,
        fontWeight: '600',
        color: colors.textPrimary,
    },
    customToolbarPreviewCard: {
        marginTop: Spacing.sm,
        padding: Spacing.sm,
        borderRadius: BorderRadius.sm,
        backgroundColor: colors.bgSecondary,
        borderWidth: 1,
        borderColor: colors.borderLight,
        gap: 6,
    },
    customToolbarPreviewLabel: {
        fontSize: FontSize.xs,
        fontWeight: '700',
        color: colors.textSecondary,
    },
    customToolbarPreviewRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: Spacing.sm,
    },
    customToolbarButtonPreview: {
        width: 36,
        height: 36,
        borderRadius: BorderRadius.sm,
        backgroundColor: colors.bgCard,
        borderWidth: 1,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    customToolbarButtonPreviewText: {
        fontSize: FontSize.sm,
        fontWeight: '700',
        color: colors.textPrimary,
    },
    customToolbarInput: { marginTop: Spacing.sm, fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace' },
    customToolbarHtmlPreview: {
        flex: 1,
        backgroundColor: colors.bgCard,
        paddingHorizontal: Spacing.xs,
        paddingVertical: 4,
        borderRadius: BorderRadius.sm,
        borderWidth: 1,
        borderColor: colors.borderLight,
    },
    customToolbarHtmlPreviewCode: {
        fontSize: 11,
        fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
        color: colors.accent,
    },
    customToolbarSecurityNote: {
        fontSize: 11,
        color: colors.textMuted,
        lineHeight: 15,
    },
    customToolbarHelpScroll: {
        maxHeight: 340,
        marginVertical: Spacing.sm,
    },
    customToolbarTemplateHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 2,
    },
    customToolbarUseChip: {
        paddingHorizontal: Spacing.sm,
        paddingVertical: 4,
        backgroundColor: colors.accentLight,
        borderRadius: BorderRadius.full,
    },
    customToolbarUseChipText: {
        fontSize: FontSize.xs,
        fontWeight: '700',
        color: colors.accent,
    },
    customToolbarPresetDesc: {
        fontSize: FontSize.xs,
        color: colors.textSecondary,
        marginBottom: 4,
    },
    customToolbarActions: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        marginTop: Spacing.md,
    },
    customToolbarActionSpacer: { flex: 1 },
    customToolbarTextAction: {
        minWidth: 58,
        minHeight: 44,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: Spacing.sm,
    },
    customToolbarTextActionLabel: { color: colors.accent, fontSize: FontSize.sm, fontWeight: '700' },
    customToolbarHelpText: { fontSize: FontSize.md, lineHeight: 22, color: colors.textSecondary },
    customToolbarTemplate: {
        marginTop: Spacing.sm,
        padding: Spacing.md,
        borderRadius: BorderRadius.sm,
        backgroundColor: colors.bgSecondary,
        borderWidth: 1,
        borderColor: colors.border,
        gap: Spacing.xs,
    },
    customToolbarTemplateTitle: { fontSize: FontSize.sm, fontWeight: '800', color: colors.textPrimary },
    customToolbarCode: {
        fontSize: FontSize.sm,
        lineHeight: 20,
        color: colors.textSecondary,
        fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.35)',
        alignItems: 'center',
        justifyContent: 'center',
        padding: Spacing.xl,
    },
    modalCard: {
        width: '100%',
        maxWidth: 440,
        backgroundColor: colors.bgCard,
        borderRadius: BorderRadius.lg,
        padding: Spacing.xl,
        ...Shadows.lg,
    },
    previewCard: {
        width: '100%',
        maxWidth: 440,
        maxHeight: '85%',
        backgroundColor: colors.bgCard,
        borderRadius: BorderRadius.lg,
        padding: Spacing.lg,
        ...Shadows.lg,
    },
    previewHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 2,
    },
    previewTitleRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
    previewTitleText: { fontSize: FontSize.lg, fontWeight: '700', color: colors.textPrimary },
    previewHeaderClose: {
        width: 32,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: BorderRadius.full,
    },
    previewHeaderCloseText: {
        fontSize: 16,
        color: colors.textMuted,
        fontWeight: '600',
    },
    previewMeta: { fontSize: FontSize.xs, color: colors.textMuted, marginBottom: Spacing.sm },
    previewToggleRow: {
        flexDirection: 'row',
        backgroundColor: colors.bgSecondary,
        borderRadius: BorderRadius.sm,
        padding: 3,
        alignSelf: 'flex-start',
        marginBottom: Spacing.sm,
        borderWidth: 1,
        borderColor: colors.borderLight,
        gap: 2,
    },
    previewToggleButton: {
        paddingHorizontal: Spacing.md,
        paddingVertical: 6,
        borderRadius: BorderRadius.sm,
    },
    previewToggleButtonActive: {
        backgroundColor: colors.accent,
    },
    previewToggleText: {
        fontSize: FontSize.sm,
        fontWeight: '600',
        color: colors.textSecondary,
    },
    previewToggleTextActive: {
        color: colors.white,
        fontWeight: '700',
    },
    previewBody: {
        backgroundColor: colors.bgSecondary,
        borderRadius: BorderRadius.md,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: colors.border,
    },
    previewCloseButton: {
        marginTop: Spacing.md,
        height: 38,
        paddingHorizontal: Spacing.xxl,
        borderRadius: BorderRadius.md,
        backgroundColor: colors.bgSecondary,
        borderWidth: 1,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
    },
    previewCloseButtonText: {
        fontSize: FontSize.sm,
        fontWeight: '600',
        color: colors.textSecondary,
    },
    modalTitle: { fontSize: FontSize.lg, fontWeight: '700', color: colors.textPrimary, marginBottom: Spacing.md },
    modalInput: {
        minHeight: 48,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: BorderRadius.sm,
        paddingHorizontal: Spacing.md,
        fontSize: FontSize.md,
        color: colors.textPrimary,
        backgroundColor: colors.bgSecondary,
    },
    modalClose: { minHeight: 48, marginTop: Spacing.sm, alignItems: 'center', justifyContent: 'center' },
    modalCloseText: { color: colors.textMuted, fontWeight: '600' },
    fieldLabelRow: { minHeight: 40, marginTop: 4, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    fieldName: { flex: 1, fontSize: FontSize.sm, fontWeight: '500', color: colors.textPrimary },
    fieldActions: { flexDirection: 'row', alignItems: 'center' },
    fieldAction: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
    fieldActionDisabled: { opacity: 0.38 },
    duplicateWarningBadge: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: colors.btnHardBg,
        borderWidth: 1,
        borderColor: colors.btnHard,
        borderRadius: BorderRadius.sm,
        padding: Spacing.sm,
        marginTop: Spacing.xs,
        gap: Spacing.sm,
    },
    duplicateWarningTextContainer: {
        flex: 1,
        gap: 2,
    },
    duplicateWarningTitle: {
        fontSize: FontSize.xs,
        fontWeight: '700',
        color: colors.textPrimary,
    },
    duplicateWarningDetail: {
        fontSize: FontSize.xs,
        color: colors.textSecondary,
        lineHeight: 16,
    },
    catalogProtectedBanner: {
        backgroundColor: colors.accentLight ?? 'rgba(10, 132, 255, 0.08)',
        borderWidth: 1,
        borderColor: colors.accent,
        borderRadius: BorderRadius.md,
        padding: Spacing.md,
        marginTop: Spacing.sm,
        marginBottom: Spacing.sm,
        gap: 6,
    },
    catalogProtectedBadge: {
        fontSize: FontSize.sm,
        fontWeight: '700',
        color: colors.accent,
    },
    catalogProtectedDescription: {
        fontSize: FontSize.xs,
        color: colors.textSecondary,
        lineHeight: 18,
    },
    });
}

export type EditorStyles = ReturnType<typeof createEditorStyles>;
