import { StyleSheet } from 'react-native';
import { BorderRadius, FontSize, Shadows, Spacing, type ColorScheme } from '../../constants/theme';

/** Styles for the deck options screen, its setting controls and its dialogs. */
export function createDeckOptionsStyles(colors: ColorScheme) {
    return StyleSheet.create({
        container: { flex: 1, backgroundColor: colors.bgPrimary },
        header: {
            minHeight: 60,
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: Spacing.sm,
            backgroundColor: colors.bgPrimary,
            borderBottomWidth: StyleSheet.hairlineWidth,
            borderBottomColor: colors.border,
        },
        headerButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
        backText: { fontSize: 34, lineHeight: 36, color: colors.accent },
        headerTitleWrap: { flex: 1, paddingHorizontal: Spacing.xs },
        headerTitle: { fontSize: FontSize.lg, fontWeight: '700', color: colors.textPrimary },
        headerSubtitle: { fontSize: FontSize.xs, color: colors.textMuted, marginTop: 1 },
        content: {
            width: '100%',
            maxWidth: 1180,
            alignSelf: 'center',
            padding: Spacing.lg,
            gap: Spacing.sm,
            paddingBottom: 72,
            flexDirection: 'row',
            flexWrap: 'wrap',
            alignItems: 'flex-start',
        },
        missing: { margin: Spacing.xl, color: colors.textMuted, fontSize: FontSize.md },

        presetToolbar: {
            width: '100%',
            flexDirection: 'row',
            alignItems: 'stretch',
            marginBottom: Spacing.sm,
        },
        presetSelector: {
            flex: 1,
            minHeight: 48,
            flexDirection: 'row',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: BorderRadius.sm,
            backgroundColor: colors.bgCard,
            paddingHorizontal: Spacing.md,
            marginRight: Spacing.sm,
        },
        presetRow: {
            width: '100%',
            minHeight: 48,
            flexDirection: 'row',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: BorderRadius.sm,
            backgroundColor: colors.bgCard,
            paddingHorizontal: Spacing.md,
            marginBottom: Spacing.sm,
        },
        presetSelectorTextWrap: { flex: 1, minWidth: 0 },
        presetSelectorLabel: {
            fontSize: 10,
            fontWeight: '700',
            letterSpacing: 0.6,
            color: colors.textMuted,
            textTransform: 'uppercase',
        },
        presetSelectorName: { fontSize: FontSize.md, fontWeight: '600', color: colors.textPrimary },
        presetSelectorMeta: { fontSize: FontSize.xs, color: colors.textMuted, marginTop: 1 },
        presetSelectorChevron: { fontSize: 18, color: colors.textMuted, marginLeft: Spacing.sm },
        savePrimary: {
            minWidth: 76,
            minHeight: 48,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: colors.accent,
            borderRadius: BorderRadius.sm,
            paddingHorizontal: Spacing.md,
        },
        savePrimaryText: { color: colors.white, fontWeight: '700', fontSize: FontSize.sm },
        presetMoreButton: {
            width: 46,
            minHeight: 48,
            alignItems: 'center',
            justifyContent: 'center',
            marginLeft: Spacing.sm,
            backgroundColor: colors.bgCard,
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: BorderRadius.sm,
        },
        presetMoreButtonText: { color: colors.textSecondary, fontSize: 15, fontWeight: '800', letterSpacing: -1 },
        saveControlDisabled: { opacity: 0.5 },
        saveStatus: {
            width: '100%',
            minHeight: 42,
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: Spacing.md,
            marginBottom: Spacing.sm,
            borderWidth: 1,
            borderRadius: BorderRadius.sm,
        },
        saveStatusPending: { backgroundColor: colors.btnHardBg, borderColor: colors.btnHard },
        saveStatusSuccess: { backgroundColor: colors.btnGoodBg, borderColor: colors.btnGood },
        saveStatusError: { backgroundColor: colors.btnAgainBg, borderColor: colors.btnAgain },
        saveStatusDot: { width: 8, height: 8, borderRadius: 4, marginRight: Spacing.sm },
        saveStatusText: { flex: 1, color: colors.textSecondary, fontSize: FontSize.xs, lineHeight: 18, fontWeight: '600' },
        saveStatusHidden: { opacity: 0, borderWidth: 0, backgroundColor: 'transparent' },

        optionCard: {
            width: '100%',
            backgroundColor: colors.bgCard,
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: 10,
            paddingHorizontal: Spacing.lg,
            paddingTop: Spacing.md,
            paddingBottom: Spacing.sm,
            ...Shadows.sm,
        },
        optionCardWide: { width: '49.25%' },
        optionCardHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            borderBottomWidth: StyleSheet.hairlineWidth,
            borderBottomColor: colors.border,
            paddingBottom: 7,
            marginBottom: 3,
        },
        optionCardTitle: { flex: 1, minWidth: 0, fontSize: FontSize.lg, fontWeight: '700', color: colors.textPrimary },
        helpButton: {
            width: 44,
            height: 44,
            alignItems: 'center',
            justifyContent: 'center',
            flexShrink: 0,
        },
        helpBadge: {
            width: 22,
            height: 22,
            borderRadius: 11,
            alignItems: 'center',
            justifyContent: 'center',
            borderWidth: 1,
            borderColor: colors.accent,
            backgroundColor: colors.accentLight,
        },
        helpBadgeText: { fontSize: 13, lineHeight: 16, fontWeight: '800', color: colors.accent },
        helpOverlay: {
            flex: 1,
            justifyContent: 'flex-end',
            paddingHorizontal: Spacing.sm,
            backgroundColor: 'rgba(15, 23, 20, 0.44)',
        },
        helpSheet: {
            width: '100%',
            maxWidth: 560,
            alignSelf: 'center',
            backgroundColor: colors.bgCard,
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: BorderRadius.lg,
            paddingTop: 32,
            overflow: 'hidden',
            ...Shadows.lg,
        },
        helpSheetHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingLeft: Spacing.lg,
            paddingRight: Spacing.sm,
            paddingVertical: Spacing.sm,
            borderBottomWidth: StyleSheet.hairlineWidth,
            borderBottomColor: colors.border,
        },
        helpSheetTitleWrap: { flex: 1, minWidth: 0, paddingRight: Spacing.sm },
        helpSheetEyebrow: {
            color: colors.accent,
            fontSize: 10,
            lineHeight: 14,
            fontWeight: '800',
            letterSpacing: 1.15,
            marginBottom: 2,
        },
        helpSheetTitle: { color: colors.textPrimary, fontSize: FontSize.lg, lineHeight: 24, fontWeight: '700' },
        helpCloseButton: {
            width: 44,
            height: 44,
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: BorderRadius.full,
            backgroundColor: colors.bgInput,
        },
        helpCloseText: { color: colors.textSecondary, fontSize: 28, lineHeight: 30, fontWeight: '300', marginTop: -2 },
        helpSheetScroll: { flexShrink: 1 },
        helpSheetContent: { padding: Spacing.lg, paddingBottom: Spacing.md },
        helpSummary: { color: colors.textPrimary, fontSize: FontSize.md, lineHeight: 23, fontWeight: '600' },
        helpPoints: { gap: Spacing.md, marginTop: Spacing.lg },
        helpPointRow: { flexDirection: 'row', alignItems: 'flex-start' },
        helpPointDot: {
            width: 7,
            height: 7,
            marginTop: 7,
            marginRight: Spacing.sm,
            borderRadius: 4,
            backgroundColor: colors.accent,
        },
        helpPointText: { flex: 1, color: colors.textSecondary, fontSize: FontSize.sm, lineHeight: 21 },
        helpNote: {
            marginTop: Spacing.lg,
            padding: Spacing.md,
            borderRadius: BorderRadius.sm,
            borderLeftWidth: 3,
            borderLeftColor: colors.accent,
            backgroundColor: colors.accentLight,
        },
        helpNoteLabel: { color: colors.accent, fontSize: 10, fontWeight: '800', letterSpacing: 1, marginBottom: 4 },
        helpNoteText: { color: colors.textSecondary, fontSize: FontSize.xs, lineHeight: 18 },
        helpDismissButton: {
            minHeight: 50,
            marginHorizontal: Spacing.lg,
            marginTop: Spacing.xs,
            marginBottom: Spacing.md,
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: BorderRadius.sm,
            backgroundColor: colors.accent,
        },
        helpDismissText: { color: colors.white, fontSize: FontSize.md, fontWeight: '700' },
        optionCardBody: { gap: 2 },
        settingBlock: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.borderLight, paddingVertical: 7 },
        settingRow: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.md },
        settingLabel: { flex: 1, minWidth: 0, fontSize: FontSize.sm, lineHeight: 19, color: colors.textPrimary },
        settingHint: { fontSize: 11, lineHeight: 16, color: colors.textMuted, marginTop: 2 },
        numberControl: {
            minWidth: 126,
            maxWidth: 180,
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: colors.bgInput,
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: BorderRadius.sm,
            overflow: 'hidden',
        },
        numberInput: { flex: 1, minWidth: 70, paddingVertical: 7, paddingHorizontal: 10, textAlign: 'right', color: colors.textPrimary, fontSize: FontSize.sm, fontVariant: ['tabular-nums'] as any },
        numberInputInvalid: { color: colors.btnAgain, backgroundColor: colors.btnAgainBg },
        inputSuffix: { paddingRight: 9, color: colors.textMuted, fontSize: FontSize.xs },
        fieldError: { color: colors.btnAgain, fontSize: 11, lineHeight: 16, marginTop: 3, fontWeight: '600' },
        selectControl: {
            width: 190,
            minHeight: 38,
            flexDirection: 'row',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: BorderRadius.sm,
            backgroundColor: colors.bgInput,
            paddingHorizontal: 10,
        },
        selectControlText: { flex: 1, color: colors.textPrimary, fontSize: FontSize.sm },
        selectChevron: { color: colors.textMuted, fontSize: 16 },
        selectList: { maxHeight: 380 },
        selectOption: { minHeight: 44, flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.borderLight },
        selectOptionActive: { backgroundColor: colors.accentLight },
        selectOptionText: { flex: 1, color: colors.textPrimary, fontSize: FontSize.md },
        selectCheck: { color: colors.accent, fontSize: 17, fontWeight: '700' },
        limitTabs: { flexDirection: 'row', alignSelf: 'flex-end', marginTop: 7, borderWidth: 1, borderColor: colors.border, borderRadius: BorderRadius.sm, overflow: 'hidden' },
        limitTab: { paddingVertical: 5, paddingHorizontal: 9, backgroundColor: colors.bgInput },
        limitTabActive: { backgroundColor: colors.accent },
        limitTabText: { fontSize: 10, fontWeight: '600', color: colors.textMuted },
        limitTabTextActive: { color: colors.white },
        warningBox: { backgroundColor: colors.btnHardBg, borderWidth: 1, borderColor: colors.btnHard, borderRadius: BorderRadius.sm, padding: Spacing.sm, marginTop: Spacing.sm },
        warningText: { color: colors.btnHard, fontSize: FontSize.xs, lineHeight: 17 },
        warningBoxDanger: { backgroundColor: colors.btnAgainBg, borderColor: colors.btnAgain },
        warningTextDanger: { color: colors.btnAgain },
        warningBoxInfo: { backgroundColor: colors.bgSecondary, borderColor: colors.border },
        warningTextInfo: { color: colors.textSecondary },

        parameterInput: {
            minHeight: 96,
            paddingTop: Spacing.sm,
            textAlignVertical: 'top',
            fontSize: FontSize.sm,
        },
        optimizeButton: {
            minHeight: 46,
            borderRadius: BorderRadius.sm,
            borderWidth: 1,
            borderColor: colors.accent,
            alignItems: 'center',
            justifyContent: 'center',
            marginTop: Spacing.sm,
        },
        optimizeButtonBusy: { opacity: 0.6 },
        optimizeButtonText: { color: colors.accent, fontSize: FontSize.sm, fontWeight: '700' },
        sectionTitle: {
            fontSize: 11,
            fontWeight: '700',
            letterSpacing: 1.2,
            color: colors.textMuted,
            marginTop: Spacing.lg,
        },

        presetCard: {
            backgroundColor: colors.bgCard,
            borderRadius: BorderRadius.md,
            borderWidth: 1,
            borderColor: colors.border,
            padding: Spacing.md,
            gap: 6,
            ...Shadows.sm,
        },
        presetName: { fontSize: FontSize.lg, fontWeight: '700', color: colors.textPrimary },
        presetMeta: { fontSize: FontSize.sm, color: colors.textMuted },
        presetActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
        presetBtn: {
            paddingHorizontal: Spacing.md,
            paddingVertical: 6,
            borderRadius: BorderRadius.sm,
            borderWidth: 1,
            borderColor: colors.border,
            backgroundColor: colors.bgInput,
        },
        presetBtnText: { fontSize: FontSize.sm, fontWeight: '600', color: colors.textSecondary },
        presetBtnDanger: { color: colors.btnAgain },
        subdeckBtn: { marginTop: 4, paddingVertical: 8, alignItems: 'center', borderRadius: BorderRadius.sm, backgroundColor: colors.accentLight },
        subdeckBtnText: { color: colors.accent, fontWeight: '600', fontSize: FontSize.sm },

        field: { gap: 4 },
        fieldLabel: { fontSize: FontSize.sm, fontWeight: '600', color: colors.textSecondary, marginTop: Spacing.xs },
        fieldHint: { fontSize: FontSize.xs, color: colors.textMuted },
        input: {
            minHeight: 44,
            backgroundColor: colors.bgCard,
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: BorderRadius.sm,
            paddingHorizontal: Spacing.md,
            paddingVertical: 8,
            fontSize: FontSize.md,
            color: colors.textPrimary,
        },
        descriptionInput: { minHeight: 72, textAlignVertical: 'top' },

        choiceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 2 },
        choiceChip: {
            paddingHorizontal: Spacing.md,
            paddingVertical: 6,
            borderRadius: BorderRadius.full,
            borderWidth: 1,
            borderColor: colors.border,
            backgroundColor: colors.bgCard,
        },
        choiceChipActive: { borderColor: colors.accent, backgroundColor: colors.accentLight },
        choiceText: { fontSize: FontSize.sm, color: colors.textSecondary },
        choiceTextActive: { color: colors.accent, fontWeight: '700' },

        switchRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            minHeight: 48,
            paddingVertical: 6,
        },
        switchLabel: { fontSize: FontSize.md, color: colors.textPrimary, flex: 1, marginRight: Spacing.md },

        easyDaysRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 },
        easyDay: {
            minWidth: 64,
            alignItems: 'center',
            paddingVertical: 8,
            borderRadius: BorderRadius.sm,
            borderWidth: 1,
            borderColor: colors.border,
            backgroundColor: colors.bgCard,
            gap: 2,
        },
        easyDayReduced: { backgroundColor: colors.btnHardBg, borderColor: colors.btnHard },
        easyDayOff: { backgroundColor: colors.btnAgainBg, borderColor: colors.btnAgain },
        easyDayLabel: { fontSize: FontSize.sm, fontWeight: '700', color: colors.textPrimary },
        easyDayFactor: { fontSize: 10, color: colors.textMuted },

        saveBtn: {
            marginTop: Spacing.xl,
            backgroundColor: colors.accent,
            borderRadius: BorderRadius.sm,
            paddingVertical: Spacing.md,
            alignItems: 'center',
        },
        saveBtnSmall: {
            backgroundColor: colors.accent,
            borderRadius: BorderRadius.sm,
            paddingVertical: 8,
            paddingHorizontal: Spacing.lg,
            alignItems: 'center',
        },
        saveBtnText: { fontSize: FontSize.md, fontWeight: '700', color: colors.white },
        cancelBtn: { paddingVertical: Spacing.md, alignItems: 'center' },
        cancelText: { color: colors.textMuted, fontWeight: '600' },
        modalOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.35)',
            alignItems: 'center',
            justifyContent: 'center',
            padding: Spacing.xl,
        },
        modalCard: {
            width: '100%',
            maxWidth: 420,
            backgroundColor: colors.bgCard,
            borderRadius: BorderRadius.lg,
            padding: Spacing.xl,
            gap: Spacing.sm,
            ...Shadows.lg,
        },
        modalTitle: { fontSize: FontSize.lg, fontWeight: '700', color: colors.textPrimary },
        modalDescription: { fontSize: FontSize.sm, lineHeight: 19, color: colors.textMuted },
        modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: Spacing.sm },
        actionMenu: {
            width: '100%',
            maxWidth: 340,
            backgroundColor: colors.bgCard,
            borderRadius: BorderRadius.md,
            paddingVertical: Spacing.xs,
            ...Shadows.lg,
        },
        actionMenuRow: { minHeight: 46, justifyContent: 'center', paddingHorizontal: Spacing.lg },
        actionMenuText: { fontSize: FontSize.md, color: colors.textPrimary },
        actionMenuDanger: { color: colors.btnAgain },
        presetOption: {
            paddingVertical: 11,
            borderBottomWidth: StyleSheet.hairlineWidth,
            borderBottomColor: colors.borderLight,
        },
        presetOptionText: { fontSize: FontSize.md, color: colors.textPrimary },
        presetOptionMeta: { marginTop: 2, fontSize: FontSize.xs, color: colors.textMuted },
        presetOptionActive: { color: colors.accent, fontWeight: '700' },
    });
}

export type DeckOptionsStyles = ReturnType<typeof createDeckOptionsStyles>;
