import { StyleSheet, Platform } from 'react-native';
import { Spacing, BorderRadius, FontSize, Shadows, type ColorScheme } from '../../constants/theme';

/** Styles for the card browser, its rows, bars, menus and dialogs. */
export function createBrowserStyles(colors: ColorScheme) {
    return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.bgPrimary },
    screenHeader: {
        minHeight: 56,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: Spacing.sm,
        backgroundColor: colors.bgCard,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.border,
    },
    screenTitle: { flex: 1, fontSize: FontSize.xl, fontWeight: '800', color: colors.textPrimary },
    headerSpacer: { width: 44 },
    backButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
    scopeToolbar: {
        minHeight: 68,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: Spacing.lg,
        paddingVertical: Spacing.sm,
    },
    scopeBlock: { flex: 1, minWidth: 0 },
    scopeSelector: { flexDirection: 'row', alignItems: 'center', gap: 5, minHeight: 30, maxWidth: '100%' },
    scopeSelectorText: { flexShrink: 1, color: colors.accent, fontSize: FontSize.lg, fontWeight: '800' },
    scopeSelectorCaret: { color: colors.accent, fontSize: FontSize.sm, fontWeight: '800', marginTop: 2 },
    scopeCount: { color: colors.textMuted, fontSize: FontSize.xs, marginTop: 1 },
    addCardBtn: {
        flexShrink: 0,
        backgroundColor: colors.accent,
        paddingHorizontal: Spacing.md,
        paddingVertical: 8,
        borderRadius: BorderRadius.sm,
    },
    addCardBtnText: { fontSize: FontSize.sm, fontWeight: '700', color: colors.white },
    moreButton: {
        width: 40,
        height: 40,
        flexShrink: 0,
        marginRight: -6,
        borderRadius: BorderRadius.full,
        alignItems: 'center',
        justifyContent: 'center',
    },
    moreButtonText: { color: colors.textSecondary, fontSize: 28, lineHeight: 30, fontWeight: '700' },

    searchContainer: { paddingHorizontal: Spacing.lg, marginBottom: Spacing.sm },
    searchField: {
        height: 44,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.bgCard,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: BorderRadius.sm,
        paddingLeft: Spacing.md,
        paddingRight: Spacing.xs,
    },
    searchIcon: {
        width: 18,
        height: 18,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: Spacing.sm,
    },
    searchHelpButton: {
        width: 36,
        height: 36,
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchHelpButtonText: { fontSize: FontSize.md, fontWeight: '700', color: colors.textMuted },
    searchClearButton: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.bgInput,
    },
    searchClearButtonText: { fontSize: 13, fontWeight: '700', color: colors.textMuted, lineHeight: 15 },
    searchInput: {
        flex: 1,
        minWidth: 0,
        height: '100%',
        paddingTop: 0,
        paddingBottom: 0,
        paddingHorizontal: 0,
        fontSize: FontSize.md,
        color: colors.textPrimary,
        includeFontPadding: false,
        textAlignVertical: 'center',
    },

    // flexGrow: 0 + centered content pin the chips to their natural size; otherwise the
    // row stretches into leftover space when the list below is short, inflating the chips.
    filterScroll: { minHeight: 42, maxHeight: 42, flexGrow: 0 },
    filterContent: { paddingHorizontal: Spacing.lg, gap: 6, alignItems: 'center' },
    filterChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        paddingHorizontal: Spacing.md,
        paddingVertical: 5,
        backgroundColor: colors.bgCard,
        borderRadius: BorderRadius.full,
        borderWidth: 1,
        borderColor: colors.border,
    },
    filterChipActive: { backgroundColor: colors.accentLight, borderColor: colors.accent },
    filterChipText: { fontSize: FontSize.sm, color: colors.textSecondary },
    filterChipTextActive: { color: colors.accent, fontWeight: '600' },
    filterFlagDot: { width: 10, height: 10, borderRadius: 5 },
    filterFlagDotEmpty: {
        borderWidth: 1.5,
        borderColor: colors.accent,
        backgroundColor: 'transparent',
    },

    list: { flex: 1 },
    listContent: { flexGrow: 1, paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm, gap: 3 },
    emptyState: { flex: 1, justifyContent: 'center', paddingVertical: 48, paddingHorizontal: Spacing.xl, alignItems: 'center', gap: Spacing.sm },
    emptyTitle: { color: colors.textPrimary, fontSize: FontSize.md, fontWeight: '700', textAlign: 'center' },
    emptyText: { color: colors.textSecondary, fontSize: FontSize.sm, textAlign: 'center' },
    pageLoader: { paddingVertical: Spacing.lg, alignItems: 'center', gap: Spacing.sm },
    pageLoaderText: { color: colors.textSecondary, fontSize: FontSize.sm },

    cardItem: {
        backgroundColor: colors.bgCard,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: BorderRadius.sm + 1,
        paddingVertical: 4,
        paddingHorizontal: Spacing.md - 2,
        ...Shadows.sm,
    },
    cardItemSelected: { borderColor: colors.accent, backgroundColor: colors.accentLight },
    // Anki tints the row instead of fading it: a suspended card is out of the queue, not less
    // worth reading. Fading it was the old treatment and made the text look washed out.
    cardSuspended: { backgroundColor: colors.rowSuspendedBg, borderColor: colors.streak },
    cardBuried: { backgroundColor: colors.rowBuriedBg },
    cardItemHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
    cardIcon: { fontSize: 17, marginTop: 1 },
    cardBody: { flex: 1, minWidth: 0 },
    cardQuestion: { fontSize: 13, fontWeight: '600', color: colors.textPrimary, lineHeight: 18 },
    cardMeta: { minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 2 },
    cardTopic: { flex: 1, minWidth: 0, fontSize: 11, lineHeight: 14, color: colors.textMuted },
    statusDot: { flexShrink: 0, paddingHorizontal: 6, paddingVertical: 1, borderRadius: 3 },
    statusDotText: { fontSize: 9, fontWeight: '600' },
    scheduleMeta: { fontSize: FontSize.xs, color: colors.textMuted, marginTop: 1 },
    answerSnippet: { fontSize: FontSize.sm, color: colors.textSecondary, marginTop: 2, lineHeight: 18 },
    selectionCheckbox: {
        width: 17,
        height: 17,
        marginTop: 1,
        borderRadius: 3,
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bgCard,
        alignItems: 'center',
        justifyContent: 'center',
    },
    selectionCheckboxActive: { backgroundColor: colors.accent, borderColor: colors.accent },
    selectionCheckboxTick: { color: colors.white, fontSize: 11, lineHeight: 13, fontWeight: '900' },
    cardActions: {
        width: 24,
        flexShrink: 0,
        alignItems: 'center',
        gap: 2,
    },
    editBtn: {
        width: 24,
        height: 24,
        borderRadius: 4,
        backgroundColor: colors.bgInput,
        alignItems: 'center',
        justifyContent: 'center',
    },
    editBtnText: { fontSize: 12 },
    suspendedIcon: { fontSize: 14 },
    flagIcon: { fontSize: 14 },

    expandedContent: { marginTop: Spacing.md, paddingTop: Spacing.md, borderTopWidth: 1, borderTopColor: colors.borderLight },
    answerBox: {
        backgroundColor: colors.bgInput,
        borderRadius: BorderRadius.sm,
        padding: Spacing.md,
        marginBottom: Spacing.md,
    },
    answerLabel: {
        fontSize: 9,
        fontWeight: '700',
        letterSpacing: 1,
        color: colors.accent,
        marginBottom: 4,
        textTransform: 'uppercase',
    },
    answerContent: { fontSize: FontSize.md, color: colors.textSecondary, lineHeight: 22 },
    cardDetails: { gap: 4, marginBottom: Spacing.sm },
    detailRow: { flexDirection: 'row', justifyContent: 'space-between' },
    detailLabel: { fontSize: FontSize.sm, color: colors.textMuted },
    detailValue: { fontSize: FontSize.sm, color: colors.textPrimary, fontWeight: '500' },

    suspendBtn: {
        paddingVertical: Spacing.sm,
        backgroundColor: colors.bgInput,
        borderRadius: BorderRadius.sm,
        alignItems: 'center',
    },
    suspendBtnActive: { backgroundColor: colors.accentLight },
    suspendBtnText: { fontSize: FontSize.sm, fontWeight: '600', color: colors.textSecondary },

    selectionBar: {
        minHeight: 68,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: Spacing.sm,
        paddingBottom: Spacing.xs,
        backgroundColor: colors.bgCard,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: colors.border,
        ...Shadows.lg,
    },
    selectionBarCount: {
        flex: 1,
        minWidth: 80,
        height: 52,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: Spacing.xs,
    },
    selectionBarCloseBox: {
        width: 24,
        height: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    selectionBarClose: {
        color: colors.textSecondary,
        fontSize: 24,
        lineHeight: 26,
        fontWeight: '300',
    },
    selectionBarCountText: {
        flex: 1,
        color: colors.textPrimary,
        fontSize: FontSize.sm,
        fontWeight: '700',
    },
    selectionActionsGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
    },
    selectionAction: {
        width: 60,
        height: 52,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: BorderRadius.sm,
    },
    selectionActionIconBox: {
        width: 24,
        height: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    selectionActionText: {
        color: colors.textSecondary,
        fontSize: 11,
        fontWeight: '600',
        marginTop: 3,
        textAlign: 'center',
    },
    selectionActionTextDisabled: {
        color: colors.textMuted,
    },

    selectionMenuOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0,0,0,0.32)',
    },
    selectionMenuCard: {
        maxHeight: '78%',
        paddingTop: 32,
        paddingBottom: Spacing.xl,
        overflow: 'hidden',
        backgroundColor: colors.bgCard,
        borderTopLeftRadius: BorderRadius.lg,
        borderTopRightRadius: BorderRadius.lg,
        ...Shadows.lg,
    },
    selectionMenuHeader: {
        minHeight: 58,
        flexDirection: 'row',
        alignItems: 'center',
        paddingLeft: Spacing.lg,
        paddingRight: Spacing.sm,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.border,
    },
    selectionMenuTitle: { flex: 1, color: colors.textPrimary, fontSize: FontSize.lg, fontWeight: '800' },
    selectionMenuClose: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
    selectionMenuCloseText: { color: colors.textMuted, fontSize: 30, lineHeight: 32, fontWeight: '300' },
    selectionMenuItem: {
        minHeight: 50,
        flexDirection: 'row',
        alignItems: 'center',
        gap: Spacing.sm,
        paddingHorizontal: Spacing.lg,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.borderLight,
    },
    selectionMenuIcon: { width: 28, textAlign: 'center', color: colors.accent, fontSize: 19 },
    selectionMenuText: { flex: 1, color: colors.textPrimary, fontSize: FontSize.md, fontWeight: '500' },
    selectionMenuDanger: { color: colors.btnAgain },

    overflowOverlay: {
        flex: 1,
        alignItems: 'flex-end',
        backgroundColor: 'rgba(0,0,0,0.22)',
        paddingTop: 62,
        paddingRight: Spacing.sm,
    },
    overflowMenu: {
        width: 310,
        maxWidth: '92%',
        maxHeight: '88%',
        paddingVertical: Spacing.xs,
        overflow: 'hidden',
        backgroundColor: colors.bgCard,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: BorderRadius.md,
        ...Shadows.lg,
    },
    overflowItem: {
        minHeight: 46,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: Spacing.md,
        gap: Spacing.sm,
    },
    overflowItemDisabled: { opacity: 0.38 },
    overflowItemIcon: { width: 25, textAlign: 'center', color: colors.textSecondary, fontSize: 18 },
    overflowItemText: { flex: 1, color: colors.textPrimary, fontSize: FontSize.md, fontWeight: '500' },
    overflowCheck: { color: colors.accent, fontSize: 19, fontWeight: '900' },
    overflowBadge: {
        minWidth: 22,
        height: 22,
        paddingHorizontal: 6,
        borderRadius: 11,
        overflow: 'hidden',
        textAlign: 'center',
        lineHeight: 22,
        color: colors.white,
        backgroundColor: colors.accent,
        fontSize: FontSize.xs,
        fontWeight: '800',
    },
    overflowChevron: { color: colors.textMuted, fontSize: 24, fontWeight: '400' },
    overflowSeparator: { height: StyleSheet.hairlineWidth, marginVertical: 3, backgroundColor: colors.borderLight },
    menuFlagDot: { width: 13, height: 13, borderRadius: 7 },
    menuFlagDotEmpty: {
        borderWidth: 1.5,
        borderColor: colors.textSecondary,
        backgroundColor: 'transparent',
    },
    flagDotPlaceholder: { width: 18, height: 18 },
    overflowFlagPanel: {
        marginHorizontal: Spacing.sm,
        marginBottom: Spacing.xs,
        overflow: 'hidden',
        backgroundColor: colors.bgSecondary,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: BorderRadius.sm,
    },
    overflowFlagRow: {
        minHeight: 43,
        flexDirection: 'row',
        alignItems: 'center',
        gap: Spacing.sm,
        paddingHorizontal: Spacing.sm,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.borderLight,
    },
    overflowFlagRowActive: { backgroundColor: colors.accentLight },
    overflowFlagText: { flex: 1, color: colors.textPrimary, fontSize: FontSize.sm, fontWeight: '500' },
    overflowFlagTextActive: { color: colors.accent, fontWeight: '800' },
    overflowFlagFooter: { minHeight: 38, justifyContent: 'center', paddingHorizontal: Spacing.sm },
    overflowFlagCount: { color: colors.textMuted, fontSize: FontSize.xs, fontWeight: '600' },

    modalOverlay: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: Spacing.xl,
        backgroundColor: 'rgba(0,0,0,0.38)',
    },
    modalCard: {
        width: '100%',
        maxWidth: 440,
        maxHeight: '86%',
        padding: Spacing.lg,
        overflow: 'hidden',
        backgroundColor: colors.bgCard,
        borderRadius: BorderRadius.lg,
        ...Shadows.lg,
    },
    modalTitle: { color: colors.textPrimary, fontSize: FontSize.xl, fontWeight: '800', marginBottom: Spacing.md },
    modalCaption: { color: colors.textMuted, fontSize: FontSize.sm, marginTop: -Spacing.sm, marginBottom: Spacing.sm },
    modalCloseButton: { minHeight: 46, marginTop: Spacing.sm, alignItems: 'center', justifyContent: 'center' },
    modalCloseText: { color: colors.accent, fontSize: FontSize.md, fontWeight: '700' },
    searchHelpList: { maxHeight: 420 },
    searchHelpGroupTitle: {
        color: colors.textMuted,
        fontSize: FontSize.xs,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginTop: Spacing.md,
        marginBottom: 4,
    },
    searchHelpRow: {
        minHeight: 44,
        flexDirection: 'row',
        alignItems: 'center',
        gap: Spacing.sm,
        paddingVertical: 6,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.borderLight,
    },
    searchHelpTerm: {
        color: colors.accent,
        fontSize: FontSize.sm,
        fontWeight: '700',
        fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    },
    searchHelpHint: { flex: 1, color: colors.textSecondary, fontSize: FontSize.xs, textAlign: 'right' },
    directionRow: { flexDirection: 'row', gap: Spacing.sm, marginBottom: Spacing.sm },
    directionButton: {
        flex: 1,
        minHeight: 42,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: BorderRadius.sm,
        backgroundColor: colors.bgSecondary,
    },
    directionButtonActive: { borderColor: colors.accent, backgroundColor: colors.accentLight },
    directionText: { color: colors.textSecondary, fontSize: FontSize.sm, fontWeight: '600' },
    directionTextActive: { color: colors.accent, fontWeight: '800' },
    pickerList: { maxHeight: 430 },
    pickerRow: {
        minHeight: 48,
        flexDirection: 'row',
        alignItems: 'center',
        gap: Spacing.sm,
        paddingHorizontal: Spacing.md,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.borderLight,
    },
    pickerRowActive: { backgroundColor: colors.accentLight },
    pickerRowText: { flex: 1, color: colors.textPrimary, fontSize: FontSize.md },
    pickerRowTextActive: { color: colors.accent, fontWeight: '800' },
    pickerCheck: { color: colors.accent, fontSize: 19, fontWeight: '900' },
    flagPickerCard: { maxWidth: 380 },
    flagDot: { width: 18, height: 18, borderRadius: 9, borderWidth: 1, borderColor: colors.border },
    optionRow: {
        minHeight: 68,
        flexDirection: 'row',
        alignItems: 'center',
        gap: Spacing.md,
        paddingVertical: Spacing.sm,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.borderLight,
    },
    optionCopy: { flex: 1 },
    optionTitle: { color: colors.textPrimary, fontSize: FontSize.md, fontWeight: '700' },
    optionCaption: { color: colors.textMuted, fontSize: FontSize.xs, lineHeight: 17, marginTop: 2 },
    fieldLabel: { color: colors.textSecondary, fontSize: FontSize.sm, fontWeight: '700', marginTop: Spacing.sm, marginBottom: Spacing.xs },
    dialogInput: {
        minHeight: 48,
        paddingHorizontal: Spacing.md,
        color: colors.textPrimary,
        fontSize: FontSize.md,
        backgroundColor: colors.bgSecondary,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: BorderRadius.sm,
    },
    checkboxRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginTop: Spacing.md },
    checkbox: { width: 22, height: 22, borderWidth: 1.5, borderColor: colors.border, borderRadius: 4, alignItems: 'center', justifyContent: 'center' },
    checkboxChecked: { backgroundColor: colors.accent, borderColor: colors.accent },
    checkboxPartial: { opacity: 0.8 },
    checkboxTick: { color: colors.white, fontSize: 15, lineHeight: 17, fontWeight: '900' },
    checkboxLabel: { flex: 1, color: colors.textPrimary, fontSize: FontSize.md },
    gradeRow: { minHeight: 50, flexDirection: 'row', alignItems: 'center', gap: Spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.borderLight },
    gradeDot: { width: 12, height: 12, borderRadius: 6 },
    gradeText: { color: colors.textPrimary, fontSize: FontSize.md, fontWeight: '700' },
    previewContainer: { flex: 1, backgroundColor: colors.bgPrimary },
    previewGrabberArea: { height: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.bgCard },
    previewGrabber: { width: 40, height: 4, borderRadius: 2, backgroundColor: colors.border },
    previewHeader: { minHeight: 58, flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, backgroundColor: colors.bgCard },
    previewHeaderButton: { minWidth: 54, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
    previewHeaderButtonText: { color: colors.textMuted, fontSize: 30, lineHeight: 32, fontWeight: '300' },
    previewFlipText: { color: colors.accent, fontSize: FontSize.sm, fontWeight: '800' },
    previewTitle: { flex: 1, textAlign: 'center', color: colors.textPrimary, fontSize: FontSize.lg, fontWeight: '800' },
    previewBody: { flex: 1, justifyContent: 'center', padding: Spacing.lg },
    previewNavigation: { minHeight: 64, flexDirection: 'row', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border, backgroundColor: colors.bgCard },
    previewNavButton: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    previewNavText: { color: colors.accent, fontSize: FontSize.md, fontWeight: '700' },
    searchPreviewBox: {
        minHeight: 48,
        maxHeight: 92,
        padding: Spacing.md,
        justifyContent: 'center',
        backgroundColor: colors.bgInput,
        borderRadius: BorderRadius.sm,
    },
    searchPreviewText: { color: colors.textSecondary, fontSize: FontSize.sm, fontFamily: 'monospace' },
    dialogActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: Spacing.sm, marginTop: Spacing.lg },
    dialogButton: { minWidth: 96, minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: BorderRadius.sm },
    dialogButtonPrimary: { backgroundColor: colors.accent },
    dialogButtonText: { color: colors.textSecondary, fontSize: FontSize.md, fontWeight: '700' },
    dialogButtonPrimaryText: { color: colors.white, fontSize: FontSize.md, fontWeight: '800' },
    });
}

export type BrowserStyles = ReturnType<typeof createBrowserStyles>;
