/**
 * Content-based topic rules for the BKA TUS catalog.
 *
 * The author tagged 2,175 of their 7,737 notes; the other 5,562 carry no label at all, which left
 * 69% of the catalog sitting in one undifferentiated "Genel" pile — four courses (Anatomi, FHE,
 * Patoloji, Farmakoloji) had no subdecks whatsoever. These rules place an unlabeled note by the
 * subject terms in its own text, using the standard TUS syllabus breakdown per course.
 *
 * Two properties are deliberate:
 *
 * - The author's own tag always wins. Content matching only ever runs on a note they left
 *   unlabeled, so a rule here can never move a note out of the topic they chose for it
 *   ([[bka-taxonomy-tag-first]] in lib/bkaTaxonomy.ts).
 * - Rules are precise rather than exhaustive. A term that appears across several topics is left
 *   out instead of being guessed at, so a note whose subject is not clear from its text stays in
 *   the course's "Genel" subdeck rather than being filed under a topic it may not belong to.
 *
 * Order matters inside a course: the first rule whose keyword appears claims the note, so narrow
 * topics are listed before broad ones.
 */

export interface BkaContentTopic {
    /** Subdeck name shown in the app; must also exist in the course's topic order. */
    name: string;
    /** Folded keywords. A note matches when one appears at the start of a word in its text. */
    keywords: string[];
}

const topic = (name: string, ...keywords: string[]): BkaContentTopic => ({ name, keywords });

/**
 * Fold a note's text for keyword matching: markup and cloze braces out, Turkish letters and case
 * flattened, everything that is not a letter or digit collapsed to a single space. Lower-casing
 * happens in the invariant locale on purpose — Turkish casing maps "I" to a dotless "ı".
 */
export function foldNoteText(value: string): string {
    return ` ${value
        .replace(/<[^>]+>/g, ' ')
        .replace(/\{\{c\d+(?:,\d+)*::/g, ' ')
        .replace(/\}\}/g, ' ')
        .replace(/&[a-z]+;/gi, ' ')
        .replace(/ı/g, 'i')
        .replace(/İ/g, 'i')
        .normalize('NFKD')
        .replace(/[̀-ͯ]/g, '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, ' ')
        .trim()} `;
}

export const BKA_CONTENT_TOPICS: Record<string, BkaContentTopic[]> = {
    'Anatomi BKA': [
        topic('Nöroanatomi',
            'nucleus', 'nuc', 'tractus', 'tr spino', 'tr cortico', 'tr kortiko', 'tr tecto',
            'tr rubro', 'tr vestibulo', 'tr olfactor', 'lemniscus', 'decussatio', 'commisura',
            'korteks', 'cortex', 'brodman', 'serebell', 'cerebell', 'medulla spinalis',
            'medulla oblongata', 'mesencephal', 'mezensefal', 'diencephal', 'telencephal',
            'thalamus', 'talamus', 'hipotalamus', 'hypothalam', 'epitalamus', 'pons',
            'capsula interna', 'gyrus', 'girus', 'limbik', 'hipokamp', 'hippocamp', 'amigdal',
            'bazal gangl', 'bazal cekirdek', 'striatum', 'globus pallidus', 'substantia nigra',
            'ventriculus lat', 'plexus choroideus', 'liquor', 'dura mater', 'duramater', 'arachnoid',
            'pia mater',
            'rexed', 'kranial sinir', 'kranyal sinir', 'homunculus', 'broca', 'wernicke',
            'wallenberg', 'sinus cavernosus', 'sinus sagittalis', 'sinus petrosus',
            'sinus transversus', 'sinus sigmoideus', 'circulus arteriosus', 'willis',
            'a cerebri', 'a cerebelli', 'a basillaris', 'a basilaris', 'formatio reticularis'),
        topic('Baş ve Boyun',
            'crani', 'calvaria', 'os frontale', 'os temporale', 'os occipitale', 'os parietale',
            'sphenoid', 'ethmoid', 'maxilla', 'mandibul', 'zygomatic', 'orbita', 'oculi',
            'bulbus oculi', 'retina', 'kornea', 'sklera', 'lens', 'sasilik', 'auris', 'kulak',
            'tympan', 'cochlea', 'koklea', 'labyrinth', 'stapedius',
            'nasal', 'nasalis', 'cavum nasi', 'burun', 'sinus paranasal', 'sinus frontalis', 'sinus maxillaris',
            'sinus sphenoidalis', 'pharynx', 'farinks', 'phx', 'larynx', 'larinks',
            'lingua', 'palat', 'tonsil', 'parotis', 'submandibul', 'sublingual', 'masseter',
            'pterygoid', 'temporalis', 'trigonum caroticum', 'trigonum submandibulare',
            'trigonum omoclaviculare', 'trigonum occipitale', 'trigonum musculare',
            'colli', 'boyun', 'cervicale', 'hyoid', 'sternohyoid', 'omohyoid', 'thyrohyoid',
            'sternotiroid', 'sternothyroid', 'digastric', 'mylohyoid', 'geniohyoid',
            'thyroidea', 'cricoid', 'krikoid',
            'a carotis', 'v jugularis', 'a facialis', 'a maxillaris', 'a lingualis',
            'ganglion cervicale', 'gang cervicale', 'fonticulus', 'sutura', 'asterion', 'pterion'),
        topic('Üst Ekstremite',
            'scapula', 'clavicula', 'humerus', 'radius', 'ulna', 'carpi', 'carpal', 'karpal',
            'metacarp', 'os hamatum', 'os pisiforme', 'os scaphoideum', 'omuz', 'cubiti',
            'dirsek', 'brachii', 'brachial', 'antebrachii', 'axilla', 'aksilla',
            'plexus brachialis', 'n medianus', 'n ulnaris', 'n radialis', 'n musculocutaneous',
            'n musculocutaneus', 'n axillaris', 'n thoracicus long', 'rotator', 'deltoid',
            'biceps', 'triceps', 'thenar', 'hipotenar', 'guyon', 'colles', 'erb duchenne',
            'klumpke', 'a brachialis', 'a axillaris', 'a radialis', 'a ulnaris',
            'retinaculum musculorum', 'tabatiere', 'anatomik enfiye'),
        topic('Alt Ekstremite',
            'femur', 'femoris', 'tibia', 'tibialis', 'fibula', 'fibularis', 'patella',
            'tarsal', 'metatars', 'calcaneus', 'kalkaneo', 'talus', 'kalca', 'coxae',
            'diz eklemi', 'ayak', 'pedis', 'plantar', 'gluteal', 'gluteus', 'quadriceps',
            'hamstring', 'poplite', 'n ischiadicus', 'siyatik', 'n femoralis', 'n obturatorius',
            'n peroneus', 'n saphenus', 'malleol', 'achilles', 'asil tendon', 'surales',
            'v saphena', 'a poplitea', 'a femoralis', 'lacuna vasorum', 'canalis adductorius',
            'trigonum femorale', 'inversiyon', 'eversiyon', 'ekinovarus'),
        topic('Toraks',
            'thorax', 'toraks', 'costa', 'costales', 'intercostal', 'kaburga', 'sternum',
            'mediasten', 'mediastin', 'pulmo', 'akciger', 'pleura', 'plevra', 'diaphragma',
            'diyafram', 'diapfragma', 'atrium', 'ventriculus dexter', 'ventriculus sinister',
            'coronaria', 'koroner', 'perikard', 'pericard', 'valva', 'mitral', 'trikuspid',
            'trachea', 'trakea', 'bronchus', 'bronkus', 'oesophag', 'ozofagus', 'ozefagus',
            'thymus', 'timus', 'mamma', 'arcus aorta', 'aorta ascendens', 'aorta descendens',
            'truncus pulmonalis', 'v azygos', 'v cava sup', 'ductus thoracicus', 'hilus'),
        topic('Abdomen',
            'abdomen', 'karin', 'peritoneum', 'periton', 'omentum', 'gaster', 'mide',
            'duodenum', 'jejunum', 'ileum', 'colon', 'kolon', 'cecum', 'cekum', 'appendix',
            'apandis', 'hepatis', 'hepatik', 'karaciger', 'safra', 'vesica fellea', 'pankreas',
            'pancrea', 'lien', 'splen', 'dalak', 'renalis', 'bobrek', 'ureter', 'sur renal',
            'suprarenal', 'rectus abdominis', 'linea alba', 'inguinal', 'kasik',
            'truncus coeliacus', 'mesenterica', 'mezenterik', 'portal', 'bursa omentalis',
            'morison', 'aorta abdominalis', 'v cava inf', 'umbilical', 'urakus'),
        topic('Pelvis ve Perine',
            'pelvis', 'pelvik', 'perine', 'vesica urinaria', 'mesane', 'urethra', 'uretra',
            'prostat', 'testis', 'skrotum', 'penis', 'uterus', 'ovarium', 'vagina',
            'tuba uterina', 'rectum', 'rektum', 'anal kanal', 'analis', 'sfinkter ani', 'levator ani', 'ischiorectal',
            'pudendal', 'plexus sacralis', 'a iliaca interna', 'hipogastrik',
            'fossa ischioanalis', 'diaphragma urogenitale'),
        topic('Sırt ve Omurga',
            'vertebra', 'columna', 'omurga', 'discus intervertebralis', 'lig longitudinale',
            'erector spinae', 'latissimus dorsi', 'trapezius', 'rhomboid', 'suboccipital',
            'sacrum', 'coccyx', 'atlas', 'axis', 'foramen intervertebrale', 'ligamentum flavum',
            'foramen magnum'),
    ],

    'FHE BKA': [
        topic('Embriyoloji',
            'embriyo', 'embryo', 'blastosist', 'blastokist', 'gastrulasyon', 'notokord',
            'somit', 'nöral tup', 'noral tup', 'faringeal ark', 'faringeal kese', 'plasenta',
            'plasental', 'koryon', 'chorion', 'amnion', 'vitellus', 'yolk', 'trofoblast',
            'sitotb', 'sinsityotb', 'desidua', 'organogenez', 'mullerian', 'wolf kanal',
            'urogenital sinus', 'kloak', 'brankial', 'primer villus', 'implantasyon',
            'fetal dolasim', 'ductus venosus', 'ductus arteriosus'),
        topic('Hücre ve Doku Histolojisi',
            'epitel', 'bag dokusu', 'bd ', 'kollajen', 'kolajen', 'elastik lif', 'retikuler lif',
            'fibroblast', 'kikirdak', 'kondro', 'kemik dokusu', 'osteoblast', 'osteoklast',
            'osteosit', 'desmozom', 'zonula', 'kaderin', 'katenin', 'vinkulin', 'ara filaman',
            'mikrotubul', 'aktin filament', 'bazal membran', 'bazal lamina', 'golgi',
            'endoplazmik', 'lizozom', 'peroksizom', 'sitoiskelet', 'plektin', 'keratin',
            'mikrovillus', 'stereosilya', 'kirpik', 'silya', 'perikondrium', 'periost'),
        topic('Kardiyovasküler Fizyoloji',
            'sa nod', 'av nod', 'his demeti', 'purkinje', 'kalp debisi', 'kardiyak output',
            'ejeksiyon fraksiyon', 'preload', 'afterload', 'frank starling', 'starling',
            'ekg', 'aksiyon potansiyeli faz', 'bainbridge', 'baroreseptor', 'barores',
            'vazomotor', 'kan basinci', 'kb kontrol', 'nabiz', 'kardiyak siklus',
            'diyastol', 'sistol', 'kapiller', 'endotel', 'no uretimi', 'damar direnci',
            'periferik direnc', 'venoz donus', 'poiseuille', 'vizkozite'),
        topic('Solunum Fizyolojisi',
            'solunum', 'akciger hacim', 'tidal', 'rezidüel', 'reziduel', 'vital kapasite',
            'komplians', 'surfaktan', 'sürfaktan', 'olu bosluk', 'ventilasyon perfuzyon',
            'v q', 'oksijen dissosiyasyon', 'hemoglobin satur', 'co2 tasin', 'bohr',
            'haldane', 'hipoksi', 'plevral basinc', 'spirometri', 'pletismograf',
            'fev1', 'clara', 'tip 2 pnomosit', 'pnomosit', 'bronsiol'),
        topic('Böbrek ve Sıvı-Elektrolit',
            'nefron', 'glomerul', 'gfr', 'klerens', 'proksimal tubul', 'distal tubul',
            'henle', 'toplayici kanal', 'juxtaglomerul', 'jukstaglomerul', 'makula densa',
            'renin', 'aldosteron', 'adh ', 'vazopressin', 'osmolarite', 'ozmolarite',
            'idrar', 'diurez', 'diürez', 'asit baz', 'ph dengesi', 'bikarbonat',
            'interkale', 'vasa rekta', 'inulin', 'inülin', 'para amino hippur', 'pah ',
            'filtrasyon fraksiyon', 'tubuloglomeruler'),
        topic('Sindirim Fizyolojisi',
            'gastrin', 'sekretin', 'cck', 'kolesistokinin', 'mide asit', 'pariyetal hc',
            'parietal hc', 'chief hc', 'pepsin', 'safra asidi', 'pankreas enzim',
            'motilite', 'peristal', 'mmc', 'migratuar', 'emilim', 'absorbsiyon',
            'gip ', 'motilin', 'vip ', 'enterik sinir', 'auerbach', 'meissner pleksus',
            'meissner ple',
            'tukruk', 'tükrük', 'salgi bezi', 'von ebner', 'brunner', 'lieberkuhn'),
        topic('Endokrin ve Üreme Fizyolojisi',
            'hipofiz', 'tsh', 'acth', 'fsh', 'lh ', 'prolaktin', 'growth hormon',
            'buyume hormonu', 'tiroid hormon', 'kortizol', 'katekolamin', 'insulin',
            'insülin', 'glukagon', 'paratiroid', 'pth', 'kalsitonin', 'd vitamini',
            'ostrojen', 'östrojen', 'progesteron', 'testosteron', 'menstrual', 'mens',
            'ovulasyon', 'spermatogenez', 'oogenez', 'oosit', 'granuloza', 'leydig',
            'sertoli', 'laktasyon', 'leptin', 'ghrelin', 'melatonin', 'istah'),
        topic('Kas ve Sinir Fizyolojisi',
            'sarkomer', 'aktin miyozin', 'miyozin', 'kas kasilma', 'kasilma', 'triad',
            'diad', 'ryanodin', 'dihidropiridin', 'motor unite', 'nöromuskuler kavsak',
            'noromuskuler', 'asetilkolin res', 'aksiyon potansiyeli', 'membran potansiyeli',
            'istirahat potansiyeli', 'repolarizasyon', 'depolarizasyon', 'refrakter',
            'na k atpaz', 'voltaj kapili', 'miyelin', 'nernst', 'goldman', 'sinaps',
            'kas ig', 'golgi tendon', 'refleks'),
        topic('Nörofizyoloji ve Duyular',
            'agri', 'tat ', 'nosisep', 'termoresep', 'trpv', 'merkel', 'meissner cisim',
            'meissner korpuskul', 'meissner cisim', 'pacini', 'ruffini', 'isitme', 'işitme', 'gorme', 'görme', 'koku',
            'denge', 'vestibuler', 'uyku', 'eeg', 'rem ', 'hafiza', 'bellek', 'limbik sistem',
            'serebral kan akim', 'bos ', 'huntington', 'parkinson fizyoloji'),
        topic('Kan ve İmmün Fizyolojisi',
            'eritrosit', 'alyuvar', 'lokosit', 'nötrofil', 'notrofil', 'eozinofil',
            'bazofil', 'lenfosit', 'monosit', 'trombosit', 'hemostaz', 'pihtilasma',
            'koagulasyon', 'fibrinolizin', 'kan grubu', 'eritropoez', 'hematopoez',
            'timus korteks', 'dalak beyaz pulpa', 'lenf nodu', 'kemik iligi'),
    ],

    'Patoloji BKA': [
        topic('Hematopatoloji',
            'lenfoma', 'losemi', 'lösemi', 'aml ', 'all ', 'kml ', 'kll ', 'myelom',
            'miyelom', 'hodgkin', 'reed sternberg', 'rs hc', 'mds ', 'miyelodisplastik',
            'myeloproliferatif', 'polisitemi', 'esansiyel trombositoz', 'miyelofibrozis',
            'langerhans hc histiyositoz', 'histiyositoz', 'pnh', 'aplastik anemi',
            'talasemi', 'orak hucre', 'sferositoz', 'hemofagositik'),
        topic('Nöropatoloji',
            'glioblastom', 'astrositom', 'oligodendroglio', 'ependimom', 'medulloblastom',
            'menenjiom', 'meningiom', 'schwannom', 'nörofibrom', 'norofibrom', 'kraniofarinjiom',
            'alzheimer', 'parkinson', 'lewy', 'multipl skleroz', 'als', 'huntington',
            'prion', 'creutzfeldt', 'nöral tup defekt', 'siringomiyeli', 'hidrosefali',
            'beyin tm', 'gliom', 'rabdoid tm'),
        topic('Böbrek ve Üriner Sistem Patolojisi',
            'glomerulonefrit', 'glomerulonefrit', 'nefrotik', 'nefritik', 'fsg', 'mpgn',
            'iga nefropati', 'berger', 'alport', 'ince bazal membran', 'minimal degisiklik',
            'membranoz nefropati', 'atn', 'akut tubuler', 'interstisyel nefrit',
            'renal hc li ka', 'rcc', 'wilms', 'mesana ka', 'urotelyal', 'nefroblastom',
            'polikistik bobrek', 'nefronofitizis', 'piyelonefrit', 'goodpasture'),
        topic('Genital Sistem ve Meme Patolojisi',
            'meme', 'mamma', 'fibroadenom', 'filloides', 'duktal karsinom', 'lobuler karsinom',
            'paget', 'over', 'ovaryan', 'endometri', 'serviks', 'hpv', 'cin ', 'myom',
            'leiomyom', 'teratom', 'disgerminom', 'granuloza hc li tm', 'brenner',
            'prostat', 'bph', 'seminom', 'testis tm', 'vulva', 'gestasyonel trofoblastik',
            'mol hidatiform', 'koryokarsinom', 'meigs'),
        topic('Endokrin Patoloji',
            'tiroit', 'tiroid', 'graves', 'hashimoto', 'papiller karsinom', 'folikuler karsinom',
            'medduller karsinom', 'medüller karsinom', 'paratiroid', 'adrenal', 'surrenal',
            'feokromositom', 'nöroblastom', 'noroblastom', 'cushing', 'conn', 'addison',
            'hipofiz adenom', 'men ', 'multipl endokrin', 'diabetes mellitus patoloji',
            'insulinoma', 'gastrinom', 'karsinoid', 'mccune albright'),
        topic('Gastrointestinal ve Karaciğer Patolojisi',
            'gastrit', 'gastropati', 'peptik ulser', 'ulser', 'barrett', 'ozofagus ka',
            'mide ka', 'kolon ka', 'kolorektal', 'polip', 'adenom', 'crohn', 'ulseratif kolit',
            'celiac', 'colyak', 'çölyak', 'hirschsprung', 'divertikul', 'apandisit',
            'hepatit', 'siroz', 'hepatosellüler', 'hepatosellüler', 'hcc', 'kolestaz',
            'wilson hastalig', 'hemokromatoz', 'a1at', 'safra kesesi', 'kolanjit',
            'pankreatit', 'ipmn', 'peutz', 'lynch', 'fap', 'cronkite'),
        topic('Solunum Sistemi Patolojisi',
            'akciger ka', 'ac ka', 'kucuk hc li ka', 'khak', 'kkhak', 'adenokarsinom ac',
            'skuamoz hc li ka ac', 'mezotelyoma', 'astim', 'astım', 'koah', 'amfizem',
            'bronsektazi', 'pnomoni', 'pnömoni', 'tuberkuloz patoloji', 'sarkoidoz',
            'silikozis', 'asbestoz', 'pnomokonyoz', 'idiyopatik pulmoner fibrozis',
            'ards', 'hyalen membran', 'pulmoner hipertansiyon', 'pulmoner emboli'),
        topic('Kardiyovasküler Patoloji',
            'ateroskleroz', 'aterom', 'miyokard infarktus', 'mi ', 'iskemik kalp',
            'kardiyomiyopati', 'miyokardit', 'endokardit', 'perikardit', 'romatizmal ates',
            'aschoff', 'kapak hastalig', 'vaskulit', 'anevrizma', 'diseksiyon',
            'kawasaki', 'takayasu', 'temporal arterit', 'buerger', 'wegener',
            'churg strauss', 'poliarterit', 'henoch'),
        topic('Kemik, Yumuşak Doku ve Deri Patolojisi',
            'osteosarkom', 'ewing', 'kondrosarkom', 'osteoid osteom', 'dev hc li tm',
            'osteoporoz', 'osteomalazi', 'paget kemik', 'osteomyelit', 'fibroz displazi',
            'rabdomyosarkom', 'liposarkom', 'leiomyosarkom', 'melanom', 'nevus', 'nevüs',
            'bazal hc li ka', 'skuamoz hc li ka deri', 'psoriasis', 'pemfigus',
            'liken', 'ephelis', 'lentigo', 'dermatofibrom'),
        topic('Genel Patoloji',
            'nekroz', 'apoptoz', 'hucre hasari', 'hipertrofi', 'hiperplazi', 'atrofi',
            'metaplazi', 'displazi', 'inflamasyon', 'granulom', 'yara iyilesme',
            'amiloid', 'amiloidoz', 'odem', 'ödem', 'tromboz', 'emboli', 'infarkt',
            'sok ', 'şok ', 'neoplazi', 'onkogen', 'tumor supresor', 'tümör supresör',
            'p53', 'rb ', 'apc', 'ras ', 'myc', 'bcl 2', 'telomeraz', 'anjiyogenez',
            'metastaz', 'karsinojen', 'immun yetmezlik', 'immün yetmezlik', 'scid',
            'bruton', 'digeorge', 'otoimmun', 'lupus', 'sjogren', 'skleroderma',
            'transplant rejeksiyon', 'hipersensitivite', 'lökosit adezyon',
            'lokosit adezyon', 'kalsifikasyon', 'pigment', 'lipofuksin', 'hemosiderin'),
    ],

    'Farmakoloji BKA': [
        // A card about how a drug is handled — enzymes, binding, clearance, poisoning — belongs
        // here even when it names drugs from every class as examples, so this rule runs first.
        topic('Genel Farmakoloji ve Toksikoloji',
            'farmakokinetik', 'farmakodinamik', 'biyoyararlanim', 'yarilanma omru',
            'yarilanma', 'dagilim hacmi', 'ilk gecis', 'first pass', 'presistemik',
            'pre sistemik', 'cyp', 'sitokrom', 'enzim indukleyici', 'enzim inhibitor',
            'plazma protein', 'albumin', 'alb e', 'terapotik indeks', 'ed50', 'ld50',
            'p glikoprotein', 'abc tasiyici', 'slc tasiyici', 'ozel tasiyici', 'eflux',
            'efluks', 'faz 1', 'faz 2', 'glukuronid', 'asetilasyon', 'konjugasyon',
            'on ilac', 'prodrug', 'eliminasyon', 'ilac etkilesim', 'asidik ilac',
            'bazik ilac', 'zehirlenme', 'antidot', 'toksisite', 'toksik ilac',
            'nefrotoksik', 'ototoksik', 'hepatotoksik', 'intoksikasyon', 'kurşun',
            'kursun', 'siyanur', 'metanol', 'karbonmonoksit', 'gebelikte ilac', 'teratojen'),
        topic('Otonom Sinir Sistemi İlaçları',
            'muskarinik', 'nikotinik', 'kolinerjik', 'antikolinerjik', 'atropin',
            'asetilkolinesteraz', 'neostigmin', 'piridostigmin', 'adrenerjik',
            'alfa blok', 'beta blok', 'beta agonist', 'alfa agonist', 'sempatomimetik',
            'sempatolitik', 'parasempat', 'noradrenalin', 'dopamin res', 'efedrin',
            'fenilefrin', 'klonidin', 'prazosin', 'propranolol', 'metoprolol',
            'nöromuskuler bloker', 'noromuskuler bloker', 'suksinilkolin', 'kurar'),
        topic('Antimikrobiyal İlaçlar',
            'penisilin', 'sefalosporin', 'karbapenem', 'monobaktam', 'vankomisin',
            'aminoglikozid', 'gentamisin', 'makrolid', 'eritromisin', 'azitromisin',
            'tetrasiklin', 'doksisiklin', 'kloramfenikol', 'klindamisin', 'linezolid',
            'kinolon', 'siprofloksasin', 'sulfonamid', 'trimetoprim', 'metronidazol',
            'nitrofurantoin', 'antitüberkuloz', 'antituberkuloz', 'izoniazid', 'rifamp',
            'etambutol', 'pirazinamid', 'antifungal', 'amfoterisin', 'flukonazol',
            'antiviral', 'asiklovir', 'oseltamivir', 'antiretroviral', 'ritonavir',
            'antiparaziter', 'klorokin', 'albendazol', 'ivermektin', 'beta laktamaz inh'),
        topic('Kardiyovasküler İlaçlar',
            'ace inh', 'acei', 'arb', 'sartan', 'kalsiyum kanal blok', 'verapamil',
            'diltiazem', 'amlodipin', 'nitrat', 'nitrogliserin', 'digoksin', 'digital',
            'antiaritmik', 'amiodaron', 'lidokain', 'adenozin', 'diuretik', 'diüretik',
            'furosemid', 'tiazid', 'spironolakton', 'statin', 'fibrat', 'ezetimib',
            'antikoagulan', 'heparin', 'varfarin', 'warfarin', 'doak', 'antiagregan',
            'aspirin', 'klopidogrel', 'trombolitik', 'streptokinaz', 'alteplaz',
            'sakubitril', 'ivabradin', 'hidralazin', 'nitroprussid', 'kalp yetmezlik ilac'),
        topic('Santral Sinir Sistemi İlaçları',
            'antipsikotik', 'haloperidol', 'klozapin', 'risperidon', 'antidepresan',
            'ssri', 'snri', 'trisiklik', 'maoi', 'lityum', 'lithium', 'benzodiazepin',
            'barbiturat', 'antiepileptik', 'fenitoin', 'karbamazepin', 'valproat',
            'lamotrijin', 'levetirasetam', 'anestezik', 'anestezi', 'propofol',
            'ketamin', 'halotan', 'opioid', 'morfin', 'fentanil', 'naloksan', 'naltrekson',
            'parkinson ilac', 'levodopa', 'antiparkinson', 'triptan', 'kafein',
            'amfetamin', 'kokain', 'alkol', 'bagimlilik'),
        topic('Endokrin ve Metabolizma İlaçları',
            'insulin', 'insülin', 'metformin', 'sulfonilure', 'sülfonilüre', 'glp 1',
            'dpp 4', 'sglt2', 'tiazolidindion', 'antidiyabetik', 'tiroid ilac',
            'propiltiourasil', 'metimazol', 'levotiroksin', 'kortikosteroid',
            'glukokortikoid', 'prednizolon', 'deksametazon', 'mineralokortikoid',
            'bifosfonat', 'denosumab', 'teriparatid', 'ostrojen tedavi', 'oral kontrasept',
            'tamoksifen', 'raloksifen', 'anabolik', 'gh tedavi', 'somatostatin analog',
            'orlistat', 'liraglutid', 'obezite tdv'),
        topic('Otakoidler ve Antiinflamatuar İlaçlar',
            'nsai', 'nsaii', 'cox', 'siklooksijenaz', 'parasetamol', 'asetaminofen',
            'kolsisin', 'allopurinol', 'febuksostat', 'urikozurik', 'gut ilac',
            'antihistaminik', 'histamin res', 'serotonin res', 'prostaglandin',
            'lökotrien', 'lokotrien', 'montelukast', 'bradikinin', 'dmard',
            'metotreksat', 'biyolojik ajan', 'tnf inh', 'hidroksiklorokin'),
        topic('Antineoplastik İlaçlar',
            'kemoterapi', 'alkilleyici', 'siklofosfamid', 'sisplatin', 'antimetabolit',
            '5 fu', 'metotreksat onko', 'antrasiklin', 'doksorubisin', 'bleomisin',
            'vinka', 'vinkristin', 'taksan', 'paklitaksel', 'topoizomeraz', 'etoposid',
            'tirozin kinaz inh', 'imatinib', 'trastuzumab', 'rituksimab', 'immunoterapi',
            'checkpoint', 'kemoterapi yan etki', 'antineoplastik'),
        topic('Solunum ve Sindirim Sistemi İlaçları',
            'bronkodilatator', 'bronkodilatör', 'salbutamol', 'salmeterol', 'ipratropium',
            'tiotropium', 'teofilin', 'inhale steroid', 'astim tedavi', 'koah tedavi',
            'antitussif', 'ekspektoran', 'proton pompa', 'ppi', 'omeprazol',
            'h2 res blok', 'ranitidin', 'antasit', 'sukralfat', 'antiemetik',
            'ondansetron', 'metoklopramid', 'laksatif', 'antidiyareik', 'loperamid',
            'ursodeoksikolik'),
    ],

    'Dahiliye BKA': [
        topic('Kardiyoloji',
            'kalp yetmezlik', 'ky ', 'miyokard', 'infarktus', 'akut koroner',
            'angina', 'anjina', 'aritmi', 'atriyal fibrilasyon', 'af ', 'ventrikuler tasikardi',
            'ekg', 'kapak', 'mitral', 'aort darlik', 'endokardit', 'perikardit',
            'kardiyomiyopati', 'hipertansiyon', 'ht ', 'senkop', 'ateroskleroz',
            'lipid', 'kolesterol', 'statin', 'ekokardiyografi', 'nyha', 'chads'),
        topic('Göğüs Hastalıkları',
            'koah', 'astim', 'astım', 'bronsektazi', 'pnomoni', 'pnömoni', 'tuberkuloz',
            'plevral', 'plevra', 'pnomotoraks', 'pulmoner emboli', 'pulmoner hipertansiyon',
            'ards', 'solunum yetmezlik', 'uyku apne', 'sarkoidoz', 'interstisyel akciger',
            'idiyopatik pulmoner fibroz', 'spirometri', 'fev1', 'arter kan gaz', 'hemoptizi',
            'akciger kanser', 'mezotelyoma', 'oksijen tedavi'),
        topic('Gastroenteroloji ve Hepatoloji',
            'ozofagus', 'ozefagus', 'reflu', 'reflü', 'barrett', 'gastrit', 'peptik ulser',
            'mide kanser', 'celiac', 'colyak', 'çölyak', 'crohn', 'ulseratif kolit',
            'ibs', 'irritabl barsak', 'divertikul', 'gis kanama', 'kolorektal',
            'hepatit', 'siroz', 'portal hipertansiyon', 'varis', 'ensefalopati',
            'hcc', 'kolestaz', 'safra', 'pankreatit', 'wilson', 'hemokromatoz',
            'otoimmun hepatit', 'primer bilier'),
        topic('Nefroloji',
            'bobrek yetmezlik', 'akut bobrek hasari', 'kronik bobrek', 'kbh', 'diyaliz',
            'glomerulonefrit', 'nefrotik', 'nefritik', 'proteinuri', 'hematuri',
            'tubulopati', 'renal tubuler asidoz', 'rta', 'hiponatremi', 'hipernatremi',
            'hiperkalemi', 'hipokalemi', 'asit baz', 'metabolik asidoz', 'metabolik alkaloz',
            'nefrolitiazis', 'bobrek tasi', 'polikistik bobrek', 'renal arter stenoz',
            'gfr', 'kreatinin klerens'),
        topic('Endokrinoloji',
            'diyabet', 'diabetes', 'insulin', 'insülin', 'metformin', 'hba1c',
            'diyabetik ketoasidoz', 'dka', 'hhd', 'hipoglisemi', 'tiroid', 'tiroit',
            'hipotiroid', 'hipertiroid', 'graves', 'hashimoto', 'guatr', 'paratiroid',
            'hiperkalsemi', 'hipokalsemi', 'osteoporoz', 'adrenal', 'surrenal', 'cushing',
            'addison', 'feokromositoma', 'akromegali', 'prolaktinoma', 'hipofiz',
            'diabetes insipitus', 'siadh', 'men ', 'obezite', 'metabolik sendrom'),
        topic('Hematoloji',
            'anemi', 'demir eksiklig', 'b12', 'folat', 'talasemi', 'orak hucre',
            'hemoliz', 'hemolitik', 'aplastik', 'pnh', 'trombositopeni', 'itp', 'ttp',
            'hemofili', 'von willebrand', 'dic ', 'koagulasyon', 'antikoagulan',
            'lenfoma', 'hodgkin', 'losemi', 'lösemi', 'aml ', 'kml ', 'kll ', 'all ',
            'multipl myelom', 'miyelom', 'mgus', 'polisitemi', 'miyelofibroz',
            'kemik iligi', 'kok hucre nakli', 'febril notropeni', 'kan transfuzyon'),
        topic('Romatoloji',
            'romatoid artrit', 'ra ', 'lupus', 'sle', 'sjogren', 'skleroderma',
            'sistemik skleroz', 'miyozit', 'dermatomiyozit', 'polimiyozit', 'vaskulit',
            'anca', 'behcet', 'behçet', 'ankilozan', 'spondiloartrit', 'psoriatik artrit',
            'reaktif artrit', 'gut', 'psodogut', 'osteoartrit', 'fmf', 'ailevi akdeniz',
            'polimiyaljia', 'temporal arterit', 'takayasu', 'antifosfolipid', 'anti ccp'),
        topic('Onkoloji',
            'kemoterapi', 'kanser tarama', 'tumor markir', 'tümör markır', 'metastaz',
            'paraneoplastik', 'onkolojik acil', 'tumor lizis', 'radyoterapi',
            'immunoterapi', 'evreleme', 'palyatif'),
    ],

    'Pediatri BKA': [
        topic('Yenidoğan',
            'yenidogan', 'neonatal', 'prematur', 'prematür', 'apgar', 'rds', 'surfaktan',
            'sürfaktan', 'mekonyum', 'nek ', 'nekrotizan enterokolit', 'sarilik',
            'hiperbilirubinemi', 'kernikterus', 'fototerapi', 'dogum travma',
            'perinatal asfiksi', 'hie ', 'rop ', 'bpd ', 'ivh ', 'yenidogan sepsis',
            'tarama testi', 'topuk kani'),
        topic('Metabolizma',
            'fenilketonuri', 'galaktozemi', 'maple syrup', 'akcaagac', 'organik asidemi',
            'ure siklus', 'üre siklus', 'hiperamonyemi', 'mitokondriyal hastalik',
            'glikojen depo', 'lizozomal', 'mukopolisakkarido', 'mps ', 'gaucher',
            'niemann', 'tay sachs', 'fabry', 'pompe', 'von gierke', 'peroksizomal',
            'zellweger', 'yag asidi oksidasyon', 'mcad', 'homosistinuri', 'tirozinemi'),
        topic('Genetik',
            'trizomi', 'down send', 'turner', 'klinefelter', 'edwards', 'patau',
            'delesyon', 'mikrodelesyon', 'prader willi', 'angelman', 'fragil x',
            'imprinting', 'mozaisizm', 'otozomal dominant', 'otozomal resesif',
            'x e bagli', 'mitokondriyal kalitim', 'anoploidi', 'kromozom analiz',
            'marfan', 'ehlers', 'noonan', 'williams', 'digeorge'),
        topic('Aşı ve Döküntülü Hastalıklar',
            'asi takvim', 'aşı ', 'asilama', 'kizamik', 'kızamık', 'kizamikcik', 'rubella',
            'kabakulak', 'sucicegi', 'suçiçeği', 'varisella', 'kizil', 'kızıl',
            'scarlatina', 'roseola', 'eritema infeksiyozum', 'besinci hastalik',
            'el ayak agiz', 'kawasaki', 'dokuntu', 'döküntü', 'bcg', 'kpa', 'dabt',
            'opv', 'ipv', 'hepatit b asi', 'rotavirus asi'),
        topic('Beslenme ve Gelişme',
            'anne sutu', 'anne sütü', 'emzirme', 'mama', 'tamamlayici besin',
            'buyume egrisi', 'persentil', 'boy kisalig', 'kilo alamama', 'malnutrisyon',
            'kwashiorkor', 'marasmus', 'raşitizm', 'rasitizm', 'd vitamin eksiklig',
            'demir profilaksi', 'gelisme basamak', 'gelişme basamak', 'psikomotor',
            'puberte', 'ergenlik', 'buyume hormonu eksiklig'),
        topic('Alerji ve İmmünoloji',
            'immun yetmezlik', 'immün yetmezlik', 'scid', 'bruton', 'agamaglobulinemi',
            'ortak degisken', 'cvid', 'digeorge', 'wiskott', 'ataksi telenjiektazi',
            'kronik granulomatoz', 'cgd', 'kompleman eksiklig', 'ige', 'atopi',
            'alerjik rinit', 'besin alerji', 'anafilaksi', 'anjioodem', 'anjiyoodem',
            'herediter anjioodem', 'astim cocuk', 'egzama', 'atopik dermatit'),
        topic('Kardiyoloji',
            'konjenital kalp', 'vsd', 'asd', 'pda', 'fallot', 'transpozisyon',
            'koarktasyon', 'triküspid atrezi', 'trikuspid atrezi', 'siyanotik',
            'asiyanotik', 'ustur', 'üfürüm', 'ufurum', 'romatizmal ates', 'endokardit profilaksi',
            'cocuk hipertansiyon', 'miyokardit cocuk'),
        topic('Göğüs Hastalıkları',
            'bronsiolit', 'krup', 'epiglottit', 'kistik fibroz', 'kf ', 'yabanci cisim',
            'pnomoni cocuk', 'pnömoni cocuk', 'siyah kokluk', 'bogmaca', 'boğmaca',
            'tuberkuloz cocuk', 'obstruktif uyku apne'),
        topic('Gastroenteroloji',
            'ishal', 'dehidratasyon', 'ors ', 'oral rehidr', 'gastroenterit',
            'intussusepsiyon', 'invajinasyon', 'pilor stenoz', 'hirschsprung',
            'anal atrezi', 'ozofagus atrezi', 'trakeoozofageal', 'gastroozofageal reflu',
            'celiac cocuk', 'colyak cocuk', 'inek sutu alerji', 'konstipasyon cocuk',
            'kolestaz cocuk', 'bilier atrezi'),
        topic('Nefroloji',
            'idrar yolu enf', 'vezikoureteral', 'vur ', 'hidronefroz', 'posterior uretral valv',
            'nefrotik cocuk', 'nefritik cocuk', 'psgn', 'hus ', 'hemolitik uremik',
            'enurezis', 'renal tubuler asidoz cocuk', 'bartter', 'gitelman',
            'polikistik bobrek cocuk', 'wilms'),
        topic('Nöroloji',
            'febril konvulziyon', 'epilepsi cocuk', 'infantil spazm', 'west send',
            'serebral palsi', 'noral tup', 'nöral tup', 'spina bifida', 'hidrosefali',
            'mikrosefali', 'makrosefali', 'norokutanoz', 'nörokutanöz', 'nf1', 'nf2',
            'tuberoskleroz', 'sturge weber', 'menenjit cocuk', 'guillain'),
        topic('Endokrinoloji',
            'konjenital hipotiroid', 'konjenital adrenal hiperplazi', 'kah ',
            'ambigus genital', 'erken puberte', 'gec puberte', 'gecikmis puberte',
            'tip 1 diyabet', 'buyume hormonu cocuk', 'hipoglisemi yenidogan',
            'rikets', 'psodohipoparatiroid'),
        topic('Hematoloji',
            'demir eksiklig anemi cocuk', 'talasemi cocuk', 'orak hucre cocuk',
            'g6pd', 'sferositoz', 'itp cocuk', 'hemofili cocuk', 'aplastik anemi cocuk',
            'fankoni', 'diamond blackfan', 'transient eritroblastopeni', 'hemanjiom'),
        topic('Onkoloji',
            'nöroblastom', 'noroblastom', 'wilms tm', 'retinoblastom', 'hepatoblastom',
            'rabdomyosarkom cocuk', 'ewing cocuk', 'osteosarkom cocuk', 'lenfoma cocuk',
            'all cocuk', 'beyin tm cocuk', 'langerhans cocuk'),
        topic('Romatoloji',
            'juvenil idiyopatik artrit', 'jia ', 'henoch', 'hsp ', 'kawasaki hast',
            'akut romatizmal ates', 'ara ', 'fmf cocuk', 'periyodik ates'),
    ],

    'Mikrobiyoloji BKA': [
        topic('İmmünoloji',
            'immunglobulin', 'immünglobulin', 'antikor', 'antijen', 'kompleman',
            'mhc', 'hla', 't hucre', 't hc', 'b hucre', 'b hc', 'sitokin', 'interlokin',
            'interlökin', 'hipersensitivite', 'otoimmun', 'immun tolerans', 'asi ',
            'adjuvan', 'dogal bagisik', 'kazanilmis bagisik', 'nk hucre', 'makrofaj',
            'dendritik hucre', 'timus seleksiyon', 'tcr', 'bcr', 'opsonizasyon'),
        topic('Viroloji',
            'virus', 'virüs', 'viral', 'hiv', 'hbv', 'hcv', 'hav', 'hdv', 'hev',
            'herpes', 'hsv', 'vzv', 'ebv', 'cmv', 'hpv', 'influenza', 'rotavirus',
            'norovirus', 'adenovirus', 'enterovirus', 'coxsackie', 'polio', 'kuduz',
            'rabies', 'kizamik virus', 'rubella virus', 'parvovirus', 'prion',
            'retrovirus', 'coronavirus', 'arbovirus', 'kirim kongo'),
        topic('Bakteriyoloji',
            'bakteri', 'stafilokok', 'streptokok', 'enterokok', 'neisseria', 'meningokok',
            'gonokok', 'haemophilus', 'bordetella', 'brucella', 'salmonella', 'shigella',
            'escherichia', 'e coli', 'klebsiella', 'proteus', 'pseudomonas', 'vibrio',
            'campylobacter', 'helicobacter', 'clostridium', 'bacillus', 'listeria',
            'corynebacterium', 'difteri', 'mycobacterium', 'tuberkuloz basil', 'lepra',
            'treponema', 'sifiliz', 'leptospira', 'borrelia', 'rickettsia', 'chlamydia',
            'mycoplasma', 'legionella', 'yersinia', 'enterobakteri', 'anaerop'),
        topic('Mikoloji',
            'mantar', 'candida', 'aspergillus', 'cryptococcus', 'histoplasma',
            'blastomyces', 'coccidioides', 'sporothrix', 'mucor', 'zygomyces',
            'pneumocystis', 'dermatofit', 'trichophyton', 'malassezia', 'fungal'),
        topic('Parazitoloji',
            'parazit', 'plasmodium', 'sitma', 'sıtma', 'malarya', 'toxoplasma',
            'leishmania', 'trypanosoma', 'entamoeba', 'giardia', 'cryptosporidium',
            'acanthamoeba', 'naegleria', 'trichomonas', 'echinococcus', 'kist hidatik',
            'taenia', 'schistosoma', 'fasciola', 'ascaris', 'enterobius', 'trichuris',
            'ancylostoma', 'strongyloides', 'trichinella', 'wuchereria', 'helmint'),
        topic('Genel Mikrobiyoloji',
            'sterilizasyon', 'dezenfeksiyon', 'otoklav', 'besiyeri', 'kultur',
            'kültür', 'gram boyama', 'boyama', 'antibiyogram', 'mik ', 'direnc mekanizma',
            'plazmid', 'konjugasyon', 'transdüksiyon', 'transduksiyon', 'transformasyon',
            'hastane enfeksiyon', 'bakteriyel genetik', 'hucre duvar', 'endotoksin',
            'ekzotoksin', 'kapsul', 'flagella', 'pilus', 'biyofilm'),
    ],

    'Biyokimya BKA': [
        topic('Proteinler',
            'aminoasit', 'amino asit', 'protein yapi', 'peptid', 'enzim', 'kinetik',
            'michaelis', 'km ', 'vmax', 'kompetitif inh', 'allosterik', 'izoenzim',
            'hemoglobin yapi', 'kollajen yapi', 'protein katlanma', 'saperon',
            'sanper', 'ubikitin', 'proteazom', 'elektroforez', 'transaminaz',
            'ure siklusu', 'üre siklusu', 'transaminasyon', 'deaminasyon'),
        topic('Karbonhidratlar',
            'glikoliz', 'glukoneogenez', 'glikojen', 'pentoz fosfat', 'tca',
            'krebs', 'sitrik asit', 'piruvat', 'laktat', 'oksidatif fosforilasyon',
            'elektron transport', 'atp sentaz', 'glukoz tasiy', 'glut', 'insulin sinyal',
            'monosakkarit', 'disakkarit', 'galaktoz', 'fruktoz', 'laktoz'),
        topic('Lipitler',
            'yag asidi', 'trigliserid', 'fosfolipid', 'kolesterol sentez', 'lipoprotein',
            'ldl', 'hdl', 'vldl', 'silomikron', 'kilomikron', 'beta oksidasyon',
            'keton cisim', 'ketogenez', 'lipoliz', 'lipogenez', 'sfingolipid',
            'eikozanoid', 'prostaglandin sentez', 'safra asidi sentez', 'steroid sentez'),
        topic('Nükleik Asitler',
            'dna', 'rna', 'replikasyon', 'transkripsiyon', 'translasyon', 'kodon',
            'ribozom', 'trna', 'mrna', 'splicing', 'mutasyon', 'tamir mekanizma',
            'pcr', 'nukleotid', 'nükleotid', 'purin', 'pirimidin', 'telomer',
            'histon', 'kromatin', 'epigenetik', 'polimeraz'),
        topic('Hormon ve Vitaminler',
            'vitamin', 'tiamin', 'riboflavin', 'niasin', 'piridoksin', 'biotin',
            'folik asit', 'kobalamin', 'askorbik', 'retinol', 'kalsiferol', 'tokoferol',
            'k vitamin', 'eser element', 'cinko', 'çinko', 'bakir', 'selenyum',
            'hormon sinyal', 'ikinci haberci', 'camp', 'cgmp', 'g proteini',
            'tirozin kinaz res', 'nuklear reseptor'),
    ],

    'Kadın Doğum BKA': [
        topic('Obstetri',
            'gebelik', 'gebe', 'dogum', 'doğum', 'travay', 'fetal', 'fetus',
            'plasenta', 'amniyon', 'preeklampsi', 'eklampsi', 'hellp', 'gestasyonel diyabet',
            'gest dm', 'erken dogum', 'preterm', 'membran ruptur', 'emr ', 'servikal yetmezlik',
            'iugr', 'oligohidramnios', 'polihidramnios', 'deselerasyon', 'nst ',
            'biyofizik profil', 'sezaryen', 'postpartum kanama', 'ablasyo', 'plasenta previa',
            'ektopik gebelik', 'abortus', 'rh uygunsuzluk', 'antenatal', 'prenatal tarama',
            'lohusa', 'puerperal', 'laktasyon'),
        topic('Jinekolojik Onkoloji',
            'serviks kanser', 'over kanser', 'endometrium kanser', 'endometriyal kanser',
            'vulva kanser', 'vajen kanser', 'hpv', 'smear', 'pap ', 'cin ',
            'gestasyonel trofoblastik', 'mol hidatiform', 'koryokarsinom',
            'ca 125', 'epitelyal over', 'germ hucreli over', 'granuloza hucreli',
            'brenner', 'krukenberg', 'evreleme figo', 'figo'),
        topic('Kontrasepsiyon',
            'kontrasep', 'oks ', 'oral kontraseptif', 'ria ', 'rahim ici arac',
            'implanon', 'depo medroksi', 'kondom', 'tuboligasyon', 'vazektomi',
            'acil kontrasepsiyon', 'sterilizasyon yontem'),
        topic('Menopoz',
            'menopoz', 'perimenopoz', 'postmenopoz', 'hormon replasman', 'hrt ',
            'sicak basmasi', 'vazomotor semptom', 'osteoporoz menopoz', 'fsh yuksek'),
        topic('Anatomi ve Muayene',
            'pelvik muayene', 'bimanuel', 'jinekolojik muayene', 'pelvis anatomi',
            'uterus anatomi', 'over anatomi', 'vajina anatomi', 'ligament uterus',
            'pelvik taban', 'levator ani', 'perine'),
        topic('Üreme Endokrinolojisi',
            'infertilite', 'amenore', 'oligomenore', 'anovulasyon', 'pkos',
            'polikistik over', 'hirsutizm', 'hiperprolaktinemi', 'ovulasyon induksiyon',
            'ivf ', 'yardimci ureme', 'endometriozis', 'adenomyozis', 'myom',
            'anormal uterin kanama', 'aub ', 'dismenore', 'premature ovaryan'),
        topic('Jinekolojik Enfeksiyonlar',
            'vajinit', 'vajinoz', 'servisit', 'pid ', 'pelvik inflamatuar',
            'tuboovaryan', 'bartolin', 'genital herpes', 'kondilom', 'trikomonas vajinit',
            'kandida vajinit', 'gardnerella'),
    ],

    'Genel Cerrahi BKA': [
        // Perioperative care, wound healing, nutrition and staging conventions are general
        // surgery whatever organ they name as an example, so this rule runs before the organs.
        topic('Cerrahi Temel Bilimler',
            'preop', 'postop', 'post op', 'perioperatif', 'yara iyilesme', 'yara sinifla',
            'cerrahi yara', 'sutur', 'cerrahi alan enf', 'antibiyotik profilaksi',
            'sivi elektrolit', 'hiponatremi', 'hipernatremi', 'hiperkalemi', 'hipokalemi',
            'beslenme destegi', 'enteral beslenme', 'parenteral beslenme', 'asit baz',
            'transfuzyon', 'anestezi riski', 'asa skor', 'venoz tromboemboli profilaksi',
            'cikarilmis olmali', 'en az 15 ln', 'ln cikar'),
        topic('Meme',
            'meme', 'mamografi', 'fibroadenom', 'duktal karsinom', 'lobuler karsinom',
            'sentinel', 'mastektomi', 'jinekomasti', 'meme ka', 'meme kanser',
            'paget meme', 'filloides', 'mastit'),
        // Named exactly as the author's own "Tiroit" label, so both passes fill one subdeck.
        topic('Tiroit',
            'tiroit', 'tiroid', 'tiroidektomi', 'guatr', 'paratiroid', 'paratiroidektomi',
            'hiperparatiroid', 'rekurren larengeal', 'medduller tiroid', 'medüller tiroid',
            'papiller tiroid', 'folikuler tiroid', 'anaplastik tiroid'),
        topic('Özofagus ve Mide',
            'ozofagus', 'ozefagus', 'akalazya', 'zenker', 'reflu cerrahi', 'nissen',
            'hiatal herni', 'mide ka', 'gastrik ulser', 'peptik ulser cerrahi',
            'vagotomi', 'gastrektomi', 'gist', 'dumping', 'bariatrik', 'obezite cerrahi',
            'sleeve', 'gastrik bypass'),
        topic('İnce Bağırsak ve Kolorektal',
            'ince barsak', 'ib obs', 'ileus', 'obstruksiyon', 'meckel', 'apandisit',
            'kolon ka', 'rektum ka', 'kolorektal', 'kolektomi', 'rezeksiyon',
            'divertikulit', 'volvulus', 'invajinasyon', 'crohn cerrahi', 'kolit cerrahi',
            'stoma', 'kolostomi', 'ileostomi', 'anastomoz', 'kisa barsak',
            'mezenter iskemi', 'anal fissur', 'hemoroid', 'perianal fistul', 'pilonidal'),
        topic('Karaciğer, Safra ve Pankreas',
            'karaciger', 'hepatektomi', 'hcc', 'kist hidatik', 'kolelitiazis',
            'kolesistit', 'kolesistektomi', 'koledok', 'kolanjit', 'kolanjiokarsinom',
            'safra tasi', 'safra kesesi', 'pankreatit', 'pankreas ka', 'whipple',
            'psodokist', 'portal hipertansiyon cerrahi', 'splenektomi', 'dalak'),
        topic('Fıtıklar',
            'fitik', 'fıtık', 'herni', 'inguinal fitik', 'femoral fitik',
            'umbilikal fitik', 'insizyonel', 'strangulasyon', 'richter', 'littre',
            'sliding fitik', 'lichtenstein', 'hesselbach'),
        topic('Travma ve Yanık',
            'travma', 'atls', 'kanama kontrol', 'sok ', 'şok', 'yanik', 'yanık',
            'parkland', 'kompartman', 'penetran', 'kunt', 'fast ', 'laparotomi',
            'damage control', 'pnomotoraks travma', 'hemotoraks'),
        topic('Endokrin Pankreas ve Nöroendokrin',
            'insulinoma', 'gastrinom', 'zollinger', 'glukagonoma', 'vipoma',
            'somatostatinoma', 'karsinoid', 'net ', 'noroendokrin tm', 'nöroendokrin tm',
            'men 1', 'men 2'),
    ],

    'Küçük Stajlar BKA': [
        topic('Halk Sağlığı',
            'insidans', 'prevalans', 'mortalite', 'morbidite', 'olum hizi', 'olum orani',
            'epidemiyoloji', 'sensitivite', 'spesifite', 'ppd deger', 'prediktif deger',
            'olgu kontrol', 'kohort', 'kesitsel', 'randomize kontrollu', 'bias',
            'karistirici', 'karıştırıcı', 'odds', 'rolatif risk', 'nnt ', 'tarama programi',
            'bildirimi zorunlu', 'saglik gostergesi', 'demografi', 'dogurganlik hizi',
            'bebek olum hizi', 'anne olum', 'ic hastalik olcut'),
        topic('Nöroloji',
            'inme ', 'inmede', 'svo ', 'iskemik inme', 'intraserebral kanama', 'subaraknoid',
            'epilepsi', 'nobet', 'nöbet', 'status epileptikus', 'bas agri', 'migren',
            'multipl skleroz', 'ms ', 'guillain', 'myastenia', 'als ', 'parkinson',
            'demans', 'alzheimer', 'periferik norop', 'polinorop', 'radikulopati',
            'menenjit', 'ensefalit', 'wallenberg', 'foville', 'weber send', 'pprf',
            'nistagmus', 'afazi', 'apraksi', 'vertigo'),
        topic('Dermatoloji',
            'dermatit', 'egzama', 'psoriasis', 'sedef', 'liken', 'pemfigus',
            'bulloz pemfigoid', 'urtiker', 'akne', 'rozasea', 'vitiligo', 'alopesi',
            'melanom', 'bazal hucreli', 'skuamoz hucreli deri', 'nevus', 'nevüs',
            'mantar enf deri', 'tinea', 'skabies', 'uyuz', 'pedikulozis', 'siğil',
            'sigil', 'verru', 'behcet deri', 'eritema nodozum', 'stevens johnson',
            'toksik epidermal', 'dermatofit', 'seboreik'),
        topic('KBB',
            'kbb', 'kulak', 'isitme', 'işitme', 'odyo', 'rinne', 'weber test',
            'itik', 'işitme kaybı', 'otit', 'otoskleroz', 'kolesteatom', 'tinnitus',
            'burun', 'rinit', 'sinuzit', 'sinüzit', 'polip nazal', 'epistaksis',
            'nazofarenks', 'larenks', 'ses kisik', 'vokal kord', 'tonsillektomi',
            'tonsillit', 'farenjit', 'trakeotomi', 'bas boyun ka', 'tukruk bezi',
            'paranasal', 'le fort', 'meniere', 'bppv'),
        topic('Göz Hastalıkları',
            'goz', 'göz', 'kornea', 'konjonktiv', 'konjunktiv', 'katarakt', 'glokom',
            'uveit', 'retina', 'retinopati', 'makula', 'optik nörit', 'optik norit',
            'papilodem', 'sasilik', 'şaşılık', 'ambliyopi', 'refraksiyon', 'miyop',
            'hipermetrop', 'astigmat', 'gorme alani', 'pupil', 'iris', 'sklera',
            'keratit', 'blefarit', 'pterjium', 'pterygium', 'dakriyosistit'),
        topic('Ortopedi',
            'kirik', 'kırık', 'cikik', 'çıkık', 'luksasyon', 'osteomyelit',
            'septik artrit', 'menisküs', 'menisküs', 'menisk', 'bag yaralanma',
            'acl', 'rotator manset', 'donuk omuz', 'karpal tunel', 'tuzak norop',
            'skolyoz', 'kifoz', 'displazi kalca', 'gelisimsel kalca', 'perthes',
            'sfe ', 'kemik tm', 'osteosarkom', 'ewing', 'dev hc li tm',
            'osteoid osteom', 'kemik kist', 'avaskuler nekroz', 'kompartman send',
            'glenohumeral', 'ayak deformite'),
        topic('Üroloji',
            'uroloji', 'üroloji', 'bobrek tasi', 'urolitiazis', 'renal kolik',
            'mesane', 'idrar kacirma', 'inkontinans', 'bph', 'prostat', 'psa',
            'prostat ka', 'mesane ka', 'testis tm', 'varikosel', 'hidrosel',
            'testis torsiyon', 'inmemis testis', 'kriptorsidizm', 'hipospadias',
            'erektil disfonksiyon', 'uretrit', 'sistit', 'piyelonefrit', 'urosepsis',
            'nefrektomi', 'tur '),
        topic('Psikiyatri',
            'depresyon', 'bipolar', 'sizofreni', 'şizofreni', 'psikoz',
            'anksiyete', 'panik', 'obsesif', 'okb ', 'mani ', 'travma sonrasi stres',
            'tssb', 'kisilik bozuk', 'kişilik', 'yeme bozuk', 'anoreksiya nervoza',
            'bulimia', 'madde bagimlilik', 'alkol bagimlilik', 'deliryum',
            'demans psikiyatri', 'somatoform', 'konversiyon', 'uyku bozuk',
            'dikkat eksiklig', 'dehb', 'otizm', 'antidepresan', 'antipsikotik'),
        topic('Anesteziyoloji',
            'anestezi', 'genel anestezi', 'rejyonal', 'spinal anestezi', 'epidural',
            'entubasyon', 'entübasyon', 'havayolu', 'mallampati', 'asa skor',
            'lokal anestezik', 'malign hipertermi', 'postop bulanti', 'agri tedavi',
            'analjezi', 'sedasyon', 'kas gevsetici', 'inhalasyon ajan', 'mac ',
            'preoperatif degerlendirme'),
        topic('Radyoloji',
            'radyoloji', 'radyografi', 'bt ', 'bilgisayarli tomografi', 'mr ',
            'manyetik rezonans', 'usg ', 'ultrason', 'sintigrafi', 'pet ',
            'kontrast madde', 'radyasyon dozu', 'girisimsel radyoloji',
            'anjiyografi', 'floroskopi'),
        topic('Kalp-Damar Cerrahisi',
            'aort anevrizma', 'aort diseksiyon', 'debakey', 'stanford',
            'periferik arter hastalig', 'varis ven', 'derin ven tromboz',
            'bypass greft', 'kabg', 'kalp kapak cerrahi', 'ekstrakorporeal',
            'av fistul', 'karotis endarterektomi'),
        topic('Beyin Cerrahisi',
            'beyin cerrahi', 'kafa travma', 'epidural hematom', 'subdural hematom',
            'kafa ici basinc', 'kib ', 'glasgow koma', 'hidrosefali cerrahi',
            'sant ', 'disk herni', 'bel fitig', 'spinal stenoz', 'anevrizma klip',
            'beyin tm cerrahi', 'kranyotomi'),
        topic('Çocuk Cerrahisi',
            'cocuk cerrahi', 'ozofagus atrezi', 'trakeoozofageal fistul',
            'diafragma herni', 'omfalosel', 'gastrosizis', 'hirschsprung cerrahi',
            'anal atrezi', 'pilor stenoz cerrahi', 'invajinasyon cerrahi',
            'inmemis testis cerrahi', 'nekrotizan enterokolit cerrahi'),
        topic('Göğüs Cerrahisi',
            'gogus cerrahi', 'toraks cerrahi', 'akciger rezeksiyon', 'lobektomi',
            'pnomonektomi', 'pnomotoraks cerrahi', 'ampiyem', 'plevral efuzyon drenaj',
            'tup torakostomi', 'mediastinoskopi', 'mediasten kitle', 'timoma',
            'gogus duvari deformite', 'pektus'),
        topic('Fiziksel Tıp ve Rehabilitasyon',
            'rehabilitasyon', 'ftr', 'fizik tedavi', 'egzersiz tedavi', 'ortez',
            'protez', 'bel agri', 'boyun agri', 'fibromiyalji', 'miyofasyal',
            'lenfodem', 'bası yarasi', 'basi yarasi', 'spastisite', 'emg ',
            'elektromiyografi', 'yurume analiz'),
    ],
};
