import type { AppSettings, Grade } from './types';
import type { AnkiCard, ReviewLog } from './models';
import { localDayNumber, nextRolloverMs } from './ankiState';
import { memoryStateFromCardData, parseAnkiCardData } from './fsrsCardData';
import { parseDueRange, setDueDateInterval, type DueRange } from './schedulingIntervals';
import { logManualEntry, revlogFactorForScheduling } from './reviewLogger';
import { resolveSettingsForDeck } from './studyCardRows';
import {
    getAllAnkiCards,
    getAnkiCard,
    getCardsForNote,
    saveAnkiCard,
} from './noteManager';
import {
    answerStudyCard,
    resetCardsToNew,
    setCardBuried,
    setCardSuspended,
    type ResetCardOptions,
} from './studyRepository';

function selectedCards(cardIds: number[]): AnkiCard[] {
    return [...new Set(cardIds)]
        .map((cardId) => getAnkiCard(cardId))
        .filter((card): card is AnkiCard => card !== null);
}

/** In notes mode, selecting one row selects every card generated by that note. */
export function expandSelectedCardsToNotes(cardIds: number[]): number[] {
    const expanded: number[] = [];
    const seenCardIds = new Set<number>();
    const seenNoteIds = new Set<number>();

    for (const cardId of cardIds) {
        const card = getAnkiCard(cardId);
        if (!card || seenNoteIds.has(card.noteId)) continue;
        seenNoteIds.add(card.noteId);
        for (const sibling of getCardsForNote(card.noteId)) {
            if (seenCardIds.has(sibling.id)) continue;
            seenCardIds.add(sibling.id);
            expanded.push(sibling.id);
        }
    }

    return expanded;
}

/** Anki toggles every selected card based on the current (first selected) card. */
export function toggleSelectedSuspend(cardIds: number[], rolloverHour: number): number {
    const cards = selectedCards(cardIds);
    if (cards.length === 0) return 0;
    const suspend = cards[0].queue !== -1;
    for (const card of cards) setCardSuspended(card.id, suspend, rolloverHour);
    return cards.length;
}

/** AnkiDroid's Toggle Bury counterpart, also driven by the current card. */
export function toggleSelectedBury(cardIds: number[], rolloverHour: number): number {
    const cards = selectedCards(cardIds);
    if (cards.length === 0) return 0;
    const bury = cards[0].queue !== -2 && cards[0].queue !== -3;
    for (const card of cards) setCardBuried(card.id, bury, rolloverHour);
    return cards.length;
}

/**
 * Reposition selected new cards in their current browser order. When shifting is enabled, cards
 * already at/after the insertion point are moved out of the inserted range first.
 */
export function repositionSelectedNewCards(
    cardIds: number[],
    start: number,
    step: number,
    shiftExisting: boolean,
): number {
    const normalizedStart = Math.max(1, Math.floor(start) || 1);
    const normalizedStep = Math.max(1, Math.floor(step) || 1);
    const cards = selectedCards(cardIds).filter((card) => card.type === 0);
    if (cards.length === 0) return 0;
    const selectedIds = new Set(cards.map((card) => card.id));

    if (shiftExisting) {
        const shift = cards.length * normalizedStep;
        const displaced = getAllAnkiCards()
            .filter((card) => card.type === 0 && !selectedIds.has(card.id) && card.due >= normalizedStart)
            .sort((a, b) => b.due - a.due || b.id - a.id);
        for (const card of displaced) {
            saveAnkiCard({ ...card, due: card.due + shift, mod: Math.floor(Date.now() / 1000), usn: -1 });
        }
    }

    cards.forEach((card, index) => {
        saveAnkiCard({
            ...card,
            due: normalizedStart + index * normalizedStep,
            mod: Math.floor(Date.now() / 1000),
            usn: -1,
        });
    });
    return cards.length;
}

/**
 * Apply Anki's Set Due Date semantics, including ranges and the interval-forcing `!`
 * (`Collection::set_due_date`): every card becomes a review card due on the chosen day, a card
 * without an ease factor takes its preset's starting ease, and a manual log row records the change.
 *
 * Returns the bookkeeping revlog rows written, so a caller that offers undo can take them back
 * out again; the browser ignores them.
 */
export function setSelectedDueDate(cardIds: number[], range: DueRange, settings: AppSettings): ReviewLog[] {
    const cards = selectedCards(cardIds);
    const nowMs = Date.now();
    const today = localDayNumber(nowMs, settings.dayRolloverHour);
    const nextDayAtMs = nextRolloverMs(nowMs, settings.dayRolloverHour);
    const span = range.maxDays - range.minDays + 1;
    const written: ReviewLog[] = [];

    cards.forEach((card, index) => {
        // Stable spread makes a range useful and repeatable without clumping every card on one day.
        const days = range.minDays + (span <= 1 ? 0 : index % span);
        const cardData = parseAnkiCardData(card.ankiData);
        const memory = memoryStateFromCardData(cardData);
        const currentDue = card.odid ? card.odue : card.due;
        const daysUntilCurrentDue = card.queue === 1 || card.queue === 4
            ? Math.trunc((Math.floor(currentDue / 1000) - Math.floor(nextDayAtMs / 1000)) / 86_400)
            : currentDue - today;

        const ivl = setDueDateInterval({
            hasMemoryState: memory !== null,
            isReviewOrRelearning: card.type === 2 || card.type === 3,
            currentInterval: card.ivl,
            lastReviewTimeMs: cardData.lastReviewTimeSecs ? cardData.lastReviewTimeSecs * 1000 : null,
            nextDayAtMs,
            daysUntilCurrentDue,
            requestedDays: days,
            forceInterval: range.forceInterval,
        });
        const factor = card.factor > 0
            ? card.factor
            : Math.round(resolveSettingsForDeck(card.odid || card.deckId, settings).startingEase * 1000);

        const updated: AnkiCard = {
            ...card,
            type: 2,
            queue: 2,
            due: today + days,
            ivl,
            factor,
            left: 0,
            odid: 0,
            odue: 0,
            deckId: card.odid || card.deckId,
            mod: Math.floor(nowMs / 1000),
            usn: -1,
        };
        saveAnkiCard(updated);
        written.push(logManualEntry(updated, 'manual', ivl, card.ivl, revlogFactorForScheduling(memory, factor)));
    });
    return written;
}

/**
 * Anki's Reset Card for the selection: back to the new queue in selection order, review history
 * preserved. The options become the browser's defaults for next time.
 */
export function resetSelectedProgress(cardIds: number[], options: ResetCardOptions): number {
    const cards = selectedCards(cardIds);
    resetCardsToNew(cards.map((card) => card.id), options, 'browser');
    return cards.length;
}

/** Grade selected cards immediately using the normal scheduler and review log path. */
export function gradeSelectedNow(cardIds: number[], grade: Grade, settings: AppSettings): number {
    let graded = 0;
    for (const card of selectedCards(cardIds)) {
        answerStudyCard(card.id, grade, settings, 0);
        graded += 1;
    }
    return graded;
}

export { parseDueRange, setDueDateInterval, type DueRange } from './schedulingIntervals';
