import type { AppSettings, Grade } from './types';
import type { AnkiCard } from './models';
import { localDayNumber } from './ankiState';
import {
    getAllAnkiCards,
    getAnkiCard,
    getCardsForNote,
    saveAnkiCard,
} from './noteManager';
import {
    answerStudyCard,
    forgetCard,
    setCardBuried,
    setCardSuspended,
} from './studyRepository';

export interface DueRange {
    minDays: number;
    maxDays: number;
    forceInterval: boolean;
}

/** Parse Anki's browser due syntax: `5`, `3-7`, `-2`, and an optional trailing `!`. */
export function parseDueRange(input: string): DueRange | null {
    const match = input.trim().match(/^(-?\d+)(?:\s*-\s*(-?\d+))?\s*(!)?$/);
    if (!match) return null;
    const first = Number(match[1]);
    const second = match[2] === undefined ? first : Number(match[2]);
    if (!Number.isSafeInteger(first) || !Number.isSafeInteger(second)) return null;
    return {
        minDays: Math.min(first, second),
        maxDays: Math.max(first, second),
        forceInterval: match[3] === '!',
    };
}

function selectedCards(cardIds: number[]): AnkiCard[] {
    return [...new Set(cardIds)]
        .map((cardId) => getAnkiCard(cardId))
        .filter((card): card is AnkiCard => card !== null);
}

/** In notes mode, selecting one row selects every card generated by that note. */
export function expandSelectedCardsToNotes(cardIds: number[]): number[] {
    const expanded: number[] = [];
    const seenCardIds = new Set<number>();
    const seenNoteIds = new Set<number>();

    for (const cardId of cardIds) {
        const card = getAnkiCard(cardId);
        if (!card || seenNoteIds.has(card.noteId)) continue;
        seenNoteIds.add(card.noteId);
        for (const sibling of getCardsForNote(card.noteId)) {
            if (seenCardIds.has(sibling.id)) continue;
            seenCardIds.add(sibling.id);
            expanded.push(sibling.id);
        }
    }

    return expanded;
}

/** Anki toggles every selected card based on the current (first selected) card. */
export function toggleSelectedSuspend(cardIds: number[], rolloverHour: number): number {
    const cards = selectedCards(cardIds);
    if (cards.length === 0) return 0;
    const suspend = cards[0].queue !== -1;
    for (const card of cards) setCardSuspended(card.id, suspend, rolloverHour);
    return cards.length;
}

/** AnkiDroid's Toggle Bury counterpart, also driven by the current card. */
export function toggleSelectedBury(cardIds: number[], rolloverHour: number): number {
    const cards = selectedCards(cardIds);
    if (cards.length === 0) return 0;
    const bury = cards[0].queue !== -2 && cards[0].queue !== -3;
    for (const card of cards) setCardBuried(card.id, bury, rolloverHour);
    return cards.length;
}

/**
 * Reposition selected new cards in their current browser order. When shifting is enabled, cards
 * already at/after the insertion point are moved out of the inserted range first.
 */
export function repositionSelectedNewCards(
    cardIds: number[],
    start: number,
    step: number,
    shiftExisting: boolean,
): number {
    const normalizedStart = Math.max(1, Math.floor(start) || 1);
    const normalizedStep = Math.max(1, Math.floor(step) || 1);
    const cards = selectedCards(cardIds).filter((card) => card.type === 0);
    if (cards.length === 0) return 0;
    const selectedIds = new Set(cards.map((card) => card.id));

    if (shiftExisting) {
        const shift = cards.length * normalizedStep;
        const displaced = getAllAnkiCards()
            .filter((card) => card.type === 0 && !selectedIds.has(card.id) && card.due >= normalizedStart)
            .sort((a, b) => b.due - a.due || b.id - a.id);
        for (const card of displaced) {
            saveAnkiCard({ ...card, due: card.due + shift, mod: Math.floor(Date.now() / 1000), usn: -1 });
        }
    }

    cards.forEach((card, index) => {
        saveAnkiCard({
            ...card,
            due: normalizedStart + index * normalizedStep,
            mod: Math.floor(Date.now() / 1000),
            usn: -1,
        });
    });
    return cards.length;
}

/** Apply Anki's Set Due Date semantics, including ranges and the interval-forcing `!`. */
export function setSelectedDueDate(cardIds: number[], range: DueRange, settings: AppSettings): number {
    const cards = selectedCards(cardIds);
    const today = localDayNumber(Date.now(), settings.dayRolloverHour);
    const span = range.maxDays - range.minDays + 1;

    cards.forEach((card, index) => {
        // Stable spread makes a range useful and repeatable without clumping every card on one day.
        const days = range.minDays + (span <= 1 ? 0 : index % span);
        const wasNew = card.type === 0;
        saveAnkiCard({
            ...card,
            type: 2,
            queue: 2,
            due: today + days,
            ivl: wasNew || range.forceInterval ? Math.max(1, Math.abs(days)) : card.ivl,
            left: 0,
            mod: Math.floor(Date.now() / 1000),
            usn: -1,
        });
    });
    return cards.length;
}

/** Reset scheduling and append cards to the end of the new queue; review history is preserved. */
export function resetSelectedProgress(cardIds: number[], settings: AppSettings): number {
    const cards = selectedCards(cardIds);
    if (cards.length === 0) return 0;
    const selectedIds = new Set(cards.map((card) => card.id));
    let nextPosition = getAllAnkiCards()
        .filter((card) => card.type === 0 && !selectedIds.has(card.id))
        .reduce((max, card) => Math.max(max, card.due), 0) + 1;

    for (const card of cards) {
        forgetCard(card.id, settings);
        const reset = getAnkiCard(card.id);
        if (!reset) continue;
        saveAnkiCard({ ...reset, due: nextPosition++, mod: Math.floor(Date.now() / 1000), usn: -1 });
    }
    return cards.length;
}

/** Grade selected cards immediately using the normal scheduler and review log path. */
export function gradeSelectedNow(cardIds: number[], grade: Grade, settings: AppSettings): number {
    let graded = 0;
    for (const card of selectedCards(cardIds)) {
        answerStudyCard(card.id, grade, settings, 0);
        graded += 1;
    }
    return graded;
}
